/* ============================================================
 *  lang.js — Motor de Internacionalização (i18n)
 *
 *  Carregado PRIMEIRO no <body> para que __() esteja global
 *  para todos os scripts subsequentes.
 *
 *  Estrutura:
 *    - Dicionário pt (chave = texto em PT, valor = texto em PT)
 *    - Dicionário en (chave = texto em PT, valor = tradução EN)
 *    - Se a chave não existir no idioma atual, cai para PT.
 *    - Se não existir nem em PT, retorna a própria chave (fallback).
 *
 *  Como adicionar uma nova string:
 *    1. Coloque data-i18n="texto PT" no HTML (ou use __('texto PT'))
 *    2. Adicione "'texto PT': 'texto PT'" no bloco pt
 *    3. Adicione "'texto PT': 'English translation'" no bloco en
 *
 *  ATENÇÃO: Chaves com <strong>, <br/>, &amp; etc. funcionam porque
 *  translatePage() usa innerHTML (não textContent).
 * ============================================================ */
(function () {
  var LANG_KEY = 'mcookinho_lang'
  var currentLang = localStorage.getItem(LANG_KEY) || ((navigator.language || '').startsWith('pt') ? 'pt' : 'en')

  var dict = {
    /* ---- PT-BR (idioma padrão / fonte) ---- */
    pt: {
      // Identidade e meta
      'MCOOKINHO': 'MCOOKINHO',
      '[ MCOOKINHO ]': '[ MCOOKINHO ]',
      'PEU BORGES // MCOOKINHO': 'PEU BORGES // MCOOKINHO',
      'Peu Borges aka MCookinho. Engenheiro da computação, dev, criador de jogos, e pai da golden retriever Shiva.': 'Peu Borges aka MCookinho. Engenheiro da computação, dev, criador de jogos, e pai da golden retriever Shiva.',

      // Nav / Seções principais
      'MÚSICA': 'MÚSICA',
      'ABRIR BIBLIOTECA MUSICAL': 'ABRIR BIBLIOTECA MUSICAL',
      'CONQUISTAS': 'CONQUISTAS',
      'RANKINGS': 'RANKINGS',
      'Rankings baseados na minha opinião': 'Rankings baseados na minha opinião',
      'CONFIGURAÇÕES': 'CONFIGURAÇÕES',
      'IDIOMA / PREFERÊNCIAS': 'IDIOMA / PREFERÊNCIAS',
      'SOBRE': 'SOBRE',
      'STACK': 'STACK',
      'PROJETOS': 'PROJETOS',
      'JOGOS': 'JOGOS',
      'GALERIA': 'GALERIA',
      'BLOG': 'BLOG',
      'CONTATO': 'CONTATO',

      // Títulos com prefixo decorativo "//"
      '// SOBRE MIM': '// SOBRE MIM',
      '// SKILLS / STACK': '// SKILLS / STACK',
      '// PROJETOS OPEN SOURCE': '// PROJETOS OPEN SOURCE',
      '// JOGOS QUE EU FIZ': '// JOGOS QUE EU FIZ',
      '// GALERIA': '// GALERIA',
      '// BLOG': '// BLOG',
      '// CONTATO': '// CONTATO',

      // Sobre / Hero
      'SOBRE MIM': 'SOBRE MIM',
      'Fala! Sou o <strong>PEU BORGES</strong>, vulgo <strong>MisterCookie</strong> (ou MisterCookinho se tu me conhece do YouTube/Twitch). Nasci em 18/04/2005 e sou estudante de ENGENHARIA DA COMPUTAÇÃO no SENAI CIMATEC em Salvador, BA.': 'Fala! Sou o <strong>PEU BORGES</strong>, vulgo <strong>MisterCookie</strong> (ou MisterCookinho se tu me conhece do YouTube/Twitch). Nasci em 18/04/2005 e sou estudante de ENGENHARIA DA COMPUTAÇÃO no SENAI CIMATEC em Salvador, BA.',
      'Sou viciado em criar coisas! Se não é um projeto no terminal, é um jogo indie, um bot pra zoar um amigo, um sisteminha criptografado com Tor, ou um port de FNAF pro Terminal. Gosto de mostrar minhas ideias pro mundo!': 'Sou viciado em criar coisas! Se não é um projeto no terminal, é um jogo indie, um bot pra zoar um amigo, um sisteminha criptografado com Tor, ou um port de FNAF pro Terminal. Gosto de mostrar minhas ideias pro mundo!',
      'Volume alto, risada alta, café forte. E se eu sumir, tô programando às 3 da manhã ou jogando algo no Steam. SHADOW THE HEDGEHOG LITERALLY SOU EU.': 'Volume alto, risada alta, café forte. E se eu sumir, tô programando às 3 da manhã ou jogando algo no Steam. SHADOW THE HEDGEHOG LITERALLY SOU EU.',

      // Tags do about
      'XADREZ': 'XADREZ',
      'RPG DE MESA': 'RPG DE MESA',
      'GAME DEV': 'GAME DEV',
      'CAFÉ': 'CAFÉ',

      // Legendas da galeria
      'SHIVA ANDANDO': 'SHIVA ANDANDO',
      'SHIVA NADANDO': 'SHIVA NADANDO',
      'EMAS': 'EMAS',

      'SKILLS / STACK': 'SKILLS / STACK',

      // Projetos
      'PROJETOS OPEN SOURCE': 'PROJETOS OPEN SOURCE',
      '[ REPO ]': '[ REPO ]',
      'Rede social privada no terminal. Criptografado com Tor. TUI minimalista.': 'Rede social privada no terminal. Criptografado com Tor. TUI minimalista.',
      'Coleção de jogos clássicos no terminal com ncurses.': 'Coleção de jogos clássicos no terminal com ncurses.',
      'Desktop pet com IA. Um bichinho virtual inteligente que vive na sua tela.': 'Desktop pet com IA. Um bichinho virtual inteligente que vive na sua tela.',
      'Wordle Battle Royale. Descubra a palavra secreta antes dos outros em português, inglês ou espanhol.': 'Wordle Battle Royale. Descubra a palavra secreta antes dos outros em português, inglês ou espanhol.',
      'Point & Click com combate por turno. Pesque e batalhe contra os peixes do aquário.': 'Point & Click com combate por turno. Pesque e batalhe contra os peixes do aquário.',
      'Adventure game inspirado em Monkey Island. Sobreviva na floresta por 7 dias.': 'Adventure game inspirado em Monkey Island. Sobreviva na floresta por 7 dias.',
      'Puzzle game. Converta animais em criaturas da noite sem ser pego.': 'Puzzle game. Converta animais em criaturas da noite sem ser pego.',
      'Coleção de jogos clássicos no terminal com ncurses em C.': 'Coleção de jogos clássicos no terminal com ncurses em C.',
      'Seu acervo definitivo de jogos indie brasileiro — 100% Open Source.': 'Seu acervo definitivo de jogos indie brasileiro — 100% Open Source.',
      'JOGOS QUE EU FIZ': 'JOGOS QUE EU FIZ',

      // Contato
      'GITHUB': 'GITHUB',
      'LINKEDIN': 'LINKEDIN',
      'INSTAGRAM': 'INSTAGRAM',
      'TWITTER / X': 'TWITTER / X',
      'YOUTUBE': 'YOUTUBE',
      'TWITCH': 'TWITCH',
      'ITCH.IO': 'ITCH.IO',
      'STEAM': 'STEAM',

      // Blog
      'AINDA TÔ ESCREVENDO MEUS PRIMEIROS ARTIGOS': 'AINDA TÔ ESCREVENDO MEUS PRIMEIROS ARTIGOS',
      'AGUENTA AÍ QUE LOGO LOGO SAI TEXTO BOM': 'AGUENTA AÍ QUE LOGO LOGO SAI TEXTO BOM',

      // Footer / Frases
      'FEITO COM CAOS E CARINHO': 'FEITO COM CAOS E CARINHO',
      '// FEITO COM CAOS E CARINHO': '// FEITO COM CAOS E CARINHO',
      '"vivendo a vida da maneira que eu quero viver"': '"vivendo a vida da maneira que eu quero viver"',
      '// SKILL': '// SKILL',
      '★ SHIVA ★': '★ SHIVA ★',
      '🏆 // RANKINGS': '🏆 // RANKINGS',
      'PEU BORGES': 'PEU BORGES',
      'ENG. DA COMPUTAÇÃO // DEV // CRIADOR DE JOGOS': 'ENG. DA COMPUTAÇÃO // DEV // CRIADOR DE JOGOS',
      'vivendo a vida da maneira que eu quero viver': 'vivendo a vida da maneira que eu quero viver',
      'VER TODOS NO GITHUB': 'VER TODOS NO GITHUB',
      'VER NO ITCH.IO': 'VER NO ITCH.IO',

      // Skill overlay
      'SKILL': 'SKILL',
      'PROFICIÊNCIA': 'PROFICIÊNCIA',

      // Rankings tabs
      'TETRIS': 'TETRIS',
      'FILMES': 'FILMES',
      'SÉRIES': 'SÉRIES',
      'MÚSICAS': 'MÚSICAS',

      // Player
      'CARREGANDO...': 'CARREGANDO...',
      'MINHA PLAYLIST': 'MINHA PLAYLIST',
      'NENHUMA MÚSICA': 'NENHUMA MÚSICA',
      'BIBLIOTECA MUSICAL': 'BIBLIOTECA MUSICAL',
      'FECHAR': 'FECHAR',
      'VOLUME': 'VOLUME',
      'ANTERIOR': 'ANTERIOR',
      'REINICIAR': 'REINICIAR',
      'PLAY/PAUSE': 'PLAY/PAUSE',
      'PARAR': 'PARAR',
      'PRÓXIMA': 'PRÓXIMA',
      'VELOCIDADE': 'VELOCIDADE',

      // Rankings misc
      'CONTA': 'CONTA',
      'VOCÊ': 'VOCÊ',
      'SEU RECORDE': 'SEU RECORDE',
      'ORDENADO POR SCORE': 'ORDENADO POR SCORE',
      'ORDENADO POR AVALIAÇÃO PESSOAL': 'ORDENADO POR AVALIAÇÃO PESSOAL',
      'NENHUM ITEM AINDA': 'NENHUM ITEM AINDA',
      'LINES': 'LINES',
      'LEVEL': 'LEVEL',
      'OUÇA': 'OUÇA',
      'OPEN SPOTIFY': '▶ OPEN SPOTIFY',
      'SINOPSE': 'SINOPSE',
      'MINHA OPINIÃO': 'MINHA OPINIÃO',
      'EPISÓDIO FAVORITO': 'EPISÓDIO FAVORITO',

      // Tetris
      'MODO RETRO': 'MODO RETRO',
      '← → MOVER': '← → MOVER',
      '↑ ROTAR': '↑ ROTAR',
      '↓ DESCER': '↓ DESCER',
      'SPACE SOLTAR': 'SPACE SOLTAR',
      'P PAUSA': 'P PAUSA',
      'ENTER REINICIAR': 'ENTER REINICIAR',
      'GAME OVER': 'GAME OVER',
      'PRESSIONE ENTER': 'PRESSIONE ENTER',
      'PAUSA': 'PAUSA',
      '// KONAMI ACTIVATED': '// KONAMI ACTIVATED',

      // Settings
      'ATIVAR MODO NOTURNO': 'ATIVAR MODO NOTURNO',
      'ATIVAR MODO PROFISSIONAL': 'ATIVAR MODO PROFISSIONAL',
      'IDIOMA': 'IDIOMA',
      'NOTIFICAÇÕES': 'NOTIFICAÇÕES',
      'MOSTRAR': 'MOSTRAR',
      'OCULTAR': 'OCULTAR',
      'MODO PROFISSIONAL': 'MODO PROFISSIONAL',
      'ATIVAR': 'ATIVAR',

      // Achievements
      'CONQUISTA DESBLOQUEADA!': 'CONQUISTA DESBLOQUEADA!',
      'INICIANTE': 'INICIANTE',
      'INTERMEDIÁRIO': 'INTERMEDIÁRIO',
      'AVANÇADO': 'AVANÇADO',
      'EXPERT': 'EXPERT',

      // Hero / Diversos
      'ANOS': 'ANOS',
      'SALVADOR, BA': 'SALVADOR, BA',

      // Controller
      '// MEU CONTROLE FAVORITO': '// MEU CONTROLE FAVORITO',
      'Cima': 'Cima',
      'Esquerda': 'Esquerda',
      'Direita': 'Direita',
      'Baixo': 'Baixo',
      'Select': 'Select',
      'Start': 'Start',
      'Botao B': 'Botão B',
      'Botao A': 'Botão A',

      // Shiva
      'SHIVA': 'SHIVA',
      'CARINHO': 'CARINHO',
      'GOLDEN RETRIEVER, A COISA MAIS FOFA DESSE MUNDO, MINHA PARCEIRA DE CÓDIGO': 'GOLDEN RETRIEVER, A COISA MAIS FOFA DESSE MUNDO, MINHA PARCEIRA DE CÓDIGO',
      'escreve pra shiva...': 'escreve pra shiva...',
      'ENVIAR': 'ENVIAR',
      'AU!! MANDA VER AÍ!! :D': 'AU!! MANDA VER AÍ!! :D',
      'escrevendo... 🐾': 'escrevendo... 🐾',

      // Skills seções
      'LINGUAGENS': 'LINGUAGENS',
      'FERRAMENTAS': 'FERRAMENTAS',
      'VIDA': 'VIDA',

      // Playlist / player
      '// MINHA PLAYLIST': '// MINHA PLAYLIST',
      'MUSICAS DE JOGOS QUE EU GOSTO': 'MUSICAS DE JOGOS QUE EU GOSTO',
      'OUTRAS MUSICAS': 'OUTRAS MUSICAS',
      'ADICIONE ARQUIVOS .MP3 EM<br/><strong>ASSETS/SOUND/PLAYLIST/</strong>': 'ADICIONE ARQUIVOS .MP3 EM<br/><strong>ASSETS/SOUND/PLAYLIST/</strong>',
      'ERRO': 'ERRO',

      // Professional mode
      'MODO — PROFISSIONAL': 'MODO — PROFISSIONAL',
      'CONFIGURAR': 'CONFIGURAR',
      'EXPORTAR PDF': 'EXPORTAR PDF',
      'DESATIVAR': 'DESATIVAR',
      'Ocultar barra': 'Ocultar barra',
      'Mostrar barra': 'Mostrar barra',
      'TEMA': 'TEMA',
      'PRESETS': 'PRESETS',
      'TIPOGRAFIA': 'TIPOGRAFIA',
      'CABEÇALHO': 'CABEÇALHO',
      'LAYOUT': 'LAYOUT',
      'CONTEÚDO': 'CONTEÚDO',
      'PDF': 'PDF',
      'SALVAR': 'SALVAR',
      'COMPARTILHAR': 'COMPARTILHAR',
      'PADRÃO': 'PADRÃO',
      'SOBRE O MODO PROFISSIONAL': 'SOBRE O MODO PROFISSIONAL',
      'Criador de experiências interativas com foco em gameplay e narrativa. Desenvolvo jogos utilizando Godot, Unity e engines próprias em C++.': '',
      'CATEGORY': 'CATEGORY',

      // Professional config labels
      'CORES PERSONALIZADAS': 'CORES PERSONALIZADAS',
      'IMAGEM DE FUNDO': 'IMAGEM DE FUNDO',
      'PADRÃO DE FUNDO': 'PADRÃO DE FUNDO',
      'OPACIDADE DO PADRÃO': 'OPACIDADE DO PADRÃO',
      'ANIMAÇÕES': 'ANIMAÇÕES',
      'PRESETS RÁPIDOS': 'PRESETS RÁPIDOS',
      'FAMÍLIA DA FONTE': 'FAMÍLIA DA FONTE',
      'TAMANHO DA FONTE': 'TAMANHO DA FONTE',
      'TAMANHO DO TÍTULO PRINCIPAL': 'TAMANHO DO TÍTULO PRINCIPAL',
      'TAMANHO DOS TÍTULOS DE SEÇÃO': 'TAMANHO DOS TÍTULOS DE SEÇÃO',
      'PESO DA FONTE': 'PESO DA FONTE',
      'ESPAÇAMENTO ENTRE PARÁGRAFOS': 'ESPAÇAMENTO ENTRE PARÁGRAFOS',
      'ALTURA DA LINHA': 'ALTURA DA LINHA',
      'ESPAÇAMENTO ENTRE LETRAS': 'ESPAÇAMENTO ENTRE LETRAS',
      'ALINHAMENTO DO TEXTO': 'ALINHAMENTO DO TEXTO',
      'ALINHAMENTO DO CABEÇALHO': 'ALINHAMENTO DO CABEÇALHO',
      'MOSTRAR LOCALIZAÇÃO': 'MOSTRAR LOCALIZAÇÃO',
      'MOSTRAR TÍTULO/CARGO': 'MOSTRAR TÍTULO/CARGO',
      'MOSTRAR LINKS DE CONTATO': 'MOSTRAR LINKS DE CONTATO',
      'IMAGEM DE PERFIL': 'IMAGEM DE PERFIL',
      'TAMANHO DA IMAGEM DE PERFIL': 'TAMANHO DA IMAGEM DE PERFIL',
      'LARGURA DO CONTEÚDO': 'LARGURA DO CONTEÚDO',
      'ESPAÇAMENTO ENTRE SEÇÕES': 'ESPAÇAMENTO ENTRE SEÇÕES',
      'ESPAÇAMENTO ENTRE ITENS': 'ESPAÇAMENTO ENTRE ITENS',
      'PADDING DO CONTEÚDO': 'PADDING DO CONTEÚDO',
      'ESTILO DO CABEÇALHO': 'ESTILO DO CABEÇALHO',
      'LAYOUT DAS HABILIDADES': 'LAYOUT DAS HABILIDADES',
      'LAYOUT DOS PROJETOS': 'LAYOUT DOS PROJETOS',
      'ESTILO DOS BOTÕES': 'ESTILO DOS BOTÕES',
      'ESTILO DAS LISTAS': 'ESTILO DAS LISTAS',
      'BORDA ARREDONDADA': 'BORDA ARREDONDADA',
      'SOMBRA': 'SOMBRA',
      'FUNDO ALTERNADO NAS SEÇÕES': 'FUNDO ALTERNADO NAS SEÇÕES',
      'COR DO FUNDO DA SEÇÃO': 'COR DO FUNDO DA SEÇÃO',
      'MOSTRAR BORDAS': 'MOSTRAR BORDAS',
      'MOSTRAR DIVISORES': 'MOSTRAR DIVISORES',
      'MOSTRAR BARRA DO TOPO': 'MOSTRAR BARRA DO TOPO',
      'MOSTRAR RODAPÉ': 'MOSTRAR RODAPÉ',
      'MOSTRAR PORCENTAGEM NAS HABILIDADES': 'MOSTRAR PORCENTAGEM NAS HABILIDADES',
      'NOME': 'NOME',
      'TÍTULO / CARGO': 'TÍTULO / CARGO',
      'LOCALIZAÇÃO': 'LOCALIZAÇÃO',
      'SOBRE': 'SOBRE',
      'EMAIL': 'EMAIL',
      'GITHUB (usuário ou URL)': 'GITHUB (usuário ou URL)',
      'LINKEDIN (URL)': 'LINKEDIN (URL)',
      'EXPERIÊNCIA': 'EXPERIÊNCIA',
      'FORMAÇÃO': 'FORMAÇÃO',
      'HABILIDADES': 'HABILIDADES',
      'HABILIDADES TÉCNICAS': 'HABILIDADES TÉCNICAS',
      'SEÇÕES PERSONALIZADAS': 'SEÇÕES PERSONALIZADAS',
      '+ ADICIONAR SEÇÃO': '+ ADICIONAR SEÇÃO',
      'INCLUIR NO PDF': 'INCLUIR NO PDF',
      'MARGENS': 'MARGENS',
      'TAMANHO DA FONTE NO PDF': 'TAMANHO DA FONTE NO PDF',
      'TAMANHO DA PÁGINA': 'TAMANHO DA PÁGINA',
      'CORES NO PDF': 'CORES NO PDF',
      'INCLUIR TOPO NO PDF': 'INCLUIR TOPO NO PDF',
      'Cargo': 'Cargo',
      'Empresa': 'Empresa',
      'Data': 'Data',
      'Descrição': 'Descrição',
      'Curso': 'Curso',
      'Instituição': 'Instituição',
      'Linguagem': 'Linguagem',
      'URL': 'URL',
      'Nova Seção': 'Nova Seção',
      'Seção personalizada': 'Seção personalizada',
      'Remover seção': 'Remover seção',
      'Título': 'Título',
      'Nome': 'Nome',
      'Título da seção': 'Título da seção',
      'Escreva aqui o conteúdo da seção...': 'Escreva aqui o conteúdo da seção...',
      'Erro ao gerar link': 'Erro ao gerar link',
      'Link copiado! Envie para qualquer pessoa.': 'Link copiado! Envie para qualquer pessoa.',
      'Erro ao copiar. Link: ': 'Erro ao copiar. Link: ',

      // Professional config option values
      'Profissional': 'Profissional',
      'Minimal': 'Minimal',
      'Escuro': 'Escuro',
      'Natureza': 'Natureza',
      'Pôr do Sol': 'Pôr do Sol',
      'Sistema': 'Sistema',
      'Serif': 'Serif',
      'Monoespaçada': 'Monoespaçada',
      'Extra pequena': 'Extra pequena',
      'Pequena': 'Pequena',
      'Normal': 'Normal',
      'Grande': 'Grande',
      'Extra grande': 'Extra grande',
      'Pequeno': 'Pequeno',
      'Leve': 'Leve',
      'Negrito': 'Negrito',
      'Compacto': 'Compacto',
      'Espaçoso': 'Espaçoso',
      'Espaçado': 'Espaçado',
      'Estreito': 'Estreito',
      'Largo': 'Largo',
      'Justificado': 'Justificado',
      'Fade In': 'Fade In',
      'Slide In': 'Slide In',
      'Sem animação': 'Sem animação',
      'Sim': 'Sim',
      'Não': 'Não',
      'Centro': 'Centro',
      'Nenhum': 'Nenhum',
      'Pontos': 'Pontos',
      'Linhas': 'Linhas',
      'Grade': 'Grade',
      'Médio': 'Médio',
      'Plano': 'Plano',
      'Contorno': 'Contorno',
      'Pílula': 'Pílula',
      'Simples': 'Simples',
      'Bullet': 'Bullet',
      'Ícone': 'Ícone',
      'Estreita': 'Estreita',
      'Larga': 'Larga',
      'Cheia': 'Cheia',
      'Detalhado': 'Detalhado',
      '2 Colunas': '2 Colunas',
      '3 Colunas': '3 Colunas',
      'Lista': 'Lista',
      'Nenhuma': 'Nenhuma',
      'Suave': 'Suave',
      'Forte': 'Forte',
      'Português': 'Português',
      'English': 'English',
      'Carta': 'Carta',
      'Colorido': 'Colorido',
      'Escala de cinza': 'Escala de cinza',
      'Cabeçalho': 'Cabeçalho',
      'Sobre': 'Sobre',
      'Experiência': 'Experiência',
      'Formação': 'Formação',
      'Projetos': 'Projetos',

      // Professional preset categories
      '🎮 Jogos': '🎮 Jogos',
      '💼 Corporativo': '💼 Corporativo',
      '📢 Marketing': '📢 Marketing',
      '💻 Programação': '💻 Programação',

      // Professional preset descriptions
      'Escuro com laranja neon. Perfeito para dev de jogos indie.': 'Escuro com laranja neon. Perfeito para dev de jogos indie.',
      'Sóbrio com acentos verde-água. Para publishers profissionais.': 'Sóbrio com acentos verde-água. Para publishers profissionais.',
      'Colorido e vibrante. Para desenvolvedor de jogos mobile.': 'Colorido e vibrante. Para desenvolvedor de jogos mobile.',
      'Agressivo e escuro. Ideal para perfil de jogador competitivo.': 'Agressivo e escuro. Ideal para perfil de jogador competitivo.',
      'Escuro com verde matrix. Portfólio de game dev.': 'Escuro com verde matrix. Portfólio de game dev.',
      'Sóbrio, azul-marinho. Para cargos de liderança.': 'Sóbrio, azul-marinho. Para cargos de liderança.',
      'Moderno com azul vibrante. Para startups de tecnologia.': 'Moderno com azul vibrante. Para startups de tecnologia.',
      'Conservador, fontes serifadas. Para banco/consultoria financeira.': 'Conservador, fontes serifadas. Para banco/consultoria financeira.',
      'Clean, profissional, minimalista.': 'Clean, profissional, minimalista.',
      'Profissional azul-escuro. Para vendas/parcerias B2B.': 'Profissional azul-escuro. Para vendas/parcerias B2B.',
      'Cores ousadas e layout moderno. Para agências de publicidade.': 'Cores ousadas e layout moderno. Para agências de publicidade.',
      'Moderno e vibrante. Para profissionais de marketing digital.': 'Moderno e vibrante. Para profissionais de marketing digital.',
      'Clean com toque trendy. Para gestor de redes sociais.': 'Clean com toque trendy. Para gestor de redes sociais.',
      'Elegante e premium. Para branding e posicionamento.': 'Elegante e premium. Para branding e posicionamento.',
      'Layout largo e moderno. Para criadores digitais.': 'Layout largo e moderno. Para criadores digitais.',
      'Dark mode com acentos azul. O clássico dev.': 'Dark mode com acentos azul. O clássico dev.',
      'Moderno e colorido. Para especialista em frontend.': 'Moderno e colorido. Para especialista em frontend.',
      'Minimalista e funcional. Sem firulas, só código.': 'Minimalista e funcional. Sem firulas, só código.',
      'Escuro com vermelho/âmbar. Estilo terminal/console.': 'Escuro com vermelho/âmbar. Estilo terminal/console.',
      'Moderno e limpo. Para desenvolvedor iOS/Android.': 'Moderno e limpo. Para desenvolvedor iOS/Android.',
      'Clean com púrpura analítico. Para área de dados.': 'Clean com púrpura analítico. Para área de dados.',
      'Verde-escuro estilo Git. Para contribuidor OSS.': 'Verde-escuro estilo Git. Para contribuidor OSS.',
      'Profissional e maduro. Para liderança técnica.': 'Profissional e maduro. Para liderança técnica.',

      // Achievement names/descriptions
      'EXPLORADOR DIGITAL': 'EXPLORADOR DIGITAL',
      'Você visitou sua primeira rede social pelo site!': 'Você visitou sua primeira rede social pelo site!',
      'Clique nos ícones de rede social no início da página...': 'Clique nos ícones de rede social no início da página...',
      'SABEDORIA PIXEL': 'SABEDORIA PIXEL',
      'Você explorou as habilidades do Peu!': 'Você explorou as habilidades do Peu!',
      'Clique em alguma skill na seção STACK...': 'Clique em alguma skill na seção STACK...',
      'PAUSA PRO CAFÉ': 'PAUSA PRO CAFÉ',
      'Você ficou mais de 5 minutos no site!': 'Você ficou mais de 5 minutos no site!',
      'Fique mais tempo explorando o site...': 'Fique mais tempo explorando o site...',
      'MELOMANIA': 'MELOMANIA',
      'Você colocou uma música para tocar!': 'Você colocou uma música para tocar!',
      'Abra a biblioteca musical e escolha uma música...': 'Abra a biblioteca musical e escolha uma música...',
      'AU!': 'AU!',
      'Você mandou sua primeira mensagem pra Shiva!': 'Você mandou sua primeira mensagem pra Shiva!',
      'Tente conversar com a Shiva no fim da página...': 'Tente conversar com a Shiva no fim da página...',
      'NOSTALGI-AÇÃO': 'NOSTALGI-AÇÃO',
      'Você apertou 10 vezes no controle NES!': 'Você apertou 10 vezes no controle NES!',
      'Fique apertando os botões do controle NES...': 'Fique apertando os botões do controle NES...',
      'BLOCO CAIU': 'BLOCO CAIU',
      'Você invocou o Tetris!': 'Você invocou o Tetris!',
      'Use o código Konami (↑↑↓↓←→←→ BA)': 'Use o código Konami (↑↑↓↓←→←→ BA)',
      'PASSEIO SOMBRIO': 'PASSEIO SOMBRIO',
      'Você enfrentou o Terror de Shiva!': 'Você enfrentou o Terror de Shiva!',
      'Tente "passear" com a Shiva...': 'Tente "passear" com a Shiva...',
      'MELHOR AMIGO': 'MELHOR AMIGO',
      'Você mandou 100 mensagens pra Shiva! Ela te ama!': 'Você mandou 100 mensagens pra Shiva! Ela te ama!',
      'Mande muuuuitas mensagens pra Shiva...': 'Mande muuuuitas mensagens pra Shiva...',
      'VICIADO EM TETRIS': 'VICIADO EM TETRIS',
      'Você fez 5.000+ pontos no Tetris!': 'Você fez 5.000+ pontos no Tetris!',
      'Jogue Tetris até passar dos 5.000 pontos...': 'Jogue Tetris até passar dos 5.000 pontos...',
      'SEM VIDA SOCIAL': 'SEM VIDA SOCIAL',
      'Você passou mais de 2 horas no site!': 'Você passou mais de 2 horas no site!',
      'Deixe o site aberto por muito tempo...': 'Deixe o site aberto por muito tempo...',
      'LENDA DO TETRIS': 'LENDA DO TETRIS',
      'Você fez 15.000+ pontos no Tetris! Lendário!': 'Você fez 15.000+ pontos no Tetris! Lendário!',
      '15.000+ pontos no Tetris... só os deuses!': '15.000+ pontos no Tetris... só os deuses!',

      // Doghouse (jogo de terror)
      'VOCÊ ESTÁ SENDO OBSERVADO': 'VOCÊ ESTÁ SENDO OBSERVADO',
      '[ CLIQUE OU TECLE ENTER PARA CONTINUAR ]': '[ CLIQUE OU TECLE ENTER PARA CONTINUAR ]',
      '◀ VIRAR ▶': '◀ VIRAR ▶',
      '[ FECHAR — ESC ]': '[ FECHAR — ESC ]',
      '[ CLIQUE PARA VOLTAR ]': '[ CLIQUE PARA VOLTAR ]',
      ' selecionado': ' selecionado',
      ' — pego.': ' — pego.',
      'Já tem isso.': 'Já tem isso.',
      'Não combina.': 'Não combina.',
      'A vela acende. A sala se revela.': 'A vela acende. A sala se revela.',
      'A chave está completa!': 'A chave está completa!',
      'A grade range! Uma guia velha cai.': 'A grade range! Uma guia velha cai.',
      'O espelho estilhaça! Um caco no chão.': 'O espelho estilhaça! Um caco no chão.',
      'Está escuro demais para ver direito.': 'Está escuro demais para ver direito.',
      'O tijolo se solta! Um fragmento de chave cai.': 'O tijolo se solta! Um fragmento de chave cai.',
      'Água escura. Não dá pra ver o fundo.': 'Água escura. Não dá pra ver o fundo.',
      ' não funciona na porta.': ' não funciona na porta.',
      ' não quebra a grade.': ' não quebra a grade.',
      'Já resolveu.': 'Já resolveu.',
      'Precisa de ': 'Precisa de ',
      ' oferecido a Shiva.': ' oferecido a Shiva.',
      'Shiva aceitou as oferendas! Fragmento de chave e coleira caem do teto.': 'Shiva aceitou as oferendas! Fragmento de chave e coleira caem do teto.',
      'A gaveta está vazia.': 'A gaveta está vazia.',
      'O ralo está vazio.': 'O ralo está vazio.',
      'Pedra': 'Pedra',
      'Caco de Vidro': 'Caco de Vidro',
      'Fósforo': 'Fósforo',
      'Vela': 'Vela',
      'Vela Acesa': 'Vela Acesa',
      'Corda': 'Corda',
      'Gancho': 'Gancho',
      'Corda com Gancho': 'Corda com Gancho',
      'Barra de Ferro': 'Barra de Ferro',
      'Fragmento de Chave I': 'Fragmento de Chave I',
      'Fragmento de Chave II': 'Fragmento de Chave II',
      'Fragmento de Chave III': 'Fragmento de Chave III',
      'Dois Fragmentos': 'Dois Fragmentos',
      'Chave Completa': 'Chave Completa',
      'Guia': 'Guia',
      'Coleira': 'Coleira',
      'Bola': 'Bola',
      'Osso': 'Osso',
      'Porta de madeira. Três fechaduras. Precisa de algo...': 'Porta de madeira. Três fechaduras. Precisa de algo...',
      'Madeira grossa, ferro, três fechaduras.': 'Madeira grossa, ferro, três fechaduras.',
      'Barras de ferro presas na parede.': 'Barras de ferro presas na parede.',
      'Pequena janela alta. Pouca luz entra.': 'Pequena janela alta. Pouca luz entra.',
      'Não há resposta.': 'Não há resposta.',
      'A caixa range quando aberta. Vazia.': 'A caixa range quando aberta. Vazia.',
      'Arranhões profundos na parede.': 'Arranhões profundos na parede.',
      'Prateleira de madeira empoeirada.': 'Prateleira de madeira empoeirada.',
      'Espelho empoeirado. Mal reflete.': 'Espelho empoeirado. Mal reflete.',
      'Tecida no canto.': 'Tecida no canto.',
      'Escuro. Ecoa.': 'Escuro. Ecoa.',
      'Algo escrito na parede.': 'Algo escrito na parede.',
      'Água escura.': 'Água escura.',
      'Tábuas soltas no chão.': 'Tábuas soltas no chão.',
      'Goteira no teto.': 'Goteira no teto.',
      'Gaveta fechada.': 'Gaveta fechada.',
      'Diário empoeirado.': 'Diário empoeirado.',
      'Bancada de trabalho coberta de ferramentas.': 'Bancada de trabalho coberta de ferramentas.',
      'Pedaço de corda pendurado.': 'Pedaço de corda pendurado.',
      'Corrente grossa pendurada no teto.': 'Corrente grossa pendurada no teto.',
      'Alçapão no teto. Trancado.': 'Alçapão no teto. Trancado.',
      'GAVETA TRANCADA — TRÊS PINOS': 'GAVETA TRANCADA — TRÊS PINOS',
      'Clique na parte de cima...': 'Clique na parte de cima...',
      'PINO ': 'PINO ',

      // Mapeamento de números hindus para puzzles
      '0': '0','1': '1','2': '2','3': '3','4': '4','5': '5','6': '6','7': '7','8': '8','9': '9',
    },

    /* ---- EN-US (traduções para inglês) ---- */
    en: {
      'MCOOKINHO': 'MCOOKINHO',
      '[ MCOOKINHO ]': '[ MCOOKINHO ]',
      'PEU BORGES // MCOOKINHO': 'PEU BORGES // MCOOKINHO',
      'Peu Borges aka MCookinho. Engenheiro da computação, dev, criador de jogos, e pai da golden retriever Shiva.': 'Peu Borges aka MCookinho. Computer engineer, dev, game creator, and golden retriever dad to Shiva.',
      'MÚSICA': 'MUSIC',
      'ABRIR BIBLIOTECA MUSICAL': 'OPEN MUSIC LIBRARY',
      'CONQUISTAS': 'ACHIEVEMENTS',
      'RANKINGS': 'RANKINGS',
      'Rankings baseados na minha opinião': 'Rankings based on my opinion',
      'CONFIGURAÇÕES': 'SETTINGS',
      'IDIOMA / PREFERÊNCIAS': 'LANGUAGE / PREFERENCES',
      'SOBRE': 'ABOUT',
      'STACK': 'STACK',
      'PROJETOS': 'PROJECTS',
      'JOGOS': 'GAMES',
      'GALERIA': 'GALLERY',
      'BLOG': 'BLOG',
      'CONTATO': 'CONTACT',
      'SOBRE MIM': 'ABOUT ME',
      'Fala! Sou o <strong>PEU BORGES</strong>, vulgo <strong>MisterCookie</strong> (ou MisterCookinho se tu me conhece do YouTube/Twitch). Nasci em 18/04/2005 e sou estudante de ENGENHARIA DA COMPUTAÇÃO no SENAI CIMATEC em Salvador, BA.': "Hey! I'm <strong>PEU BORGES</strong>, aka <strong>MisterCookie</strong> (or MisterCookinho if you know me from YouTube/Twitch). Born on 04/18/2005, I'm a Computer Engineering student at SENAI CIMATEC in Salvador, BA.",
      'Sou viciado em criar coisas! Se não é um projeto no terminal, é um jogo indie, um bot pra zoar um amigo, um sisteminha criptografado com Tor, ou um port de FNAF pro Terminal. Gosto de mostrar minhas ideias pro mundo!': "I'm addicted to creating things! If it's not a terminal project, it's an indie game, a bot to mess with a friend, a little encrypted system with Tor, or a FNAF port for the Terminal. I like showing my ideas to the world!",
      'Volume alto, risada alta, café forte. E se eu sumir, tô programando às 3 da manhã ou jogando algo no Steam. SHADOW THE HEDGEHOG LITERALLY SOU EU.': "Loud volume, loud laugh, strong coffee. And if I go quiet, I'm coding at 3 AM or playing something on Steam. SHADOW THE HEDGEHOG IS LITERALLY ME.",
      'XADREZ': 'CHESS',
      'RPG DE MESA': 'TABLE RPG',
      'GAME DEV': 'GAME DEV',
      'CAFÉ': 'COFFEE',
      'SHIVA ANDANDO': 'SHIVA WALKING',
      'SHIVA NADANDO': 'SHIVA SWIMMING',
      'EMAS': 'RHEAS',
      'SKILLS / STACK': 'SKILLS / STACK',
      'PROJETOS OPEN SOURCE': 'OPEN SOURCE PROJECTS',
      '[ REPO ]': '[ REPO ]',
      'Rede social privada no terminal. Criptografado com Tor. TUI minimalista.': 'Private social network in the terminal. Encrypted with Tor. Minimalist TUI.',
      'Coleção de jogos clássicos no terminal com ncurses.': 'Collection of classic games in the terminal with ncurses.',
      'Desktop pet com IA. Um bichinho virtual inteligente que vive na sua tela.': 'Desktop pet with AI. A smart virtual buddy that lives on your screen.',
      'Wordle Battle Royale. Descubra a palavra secreta antes dos outros em português, inglês ou espanhol.': 'Wordle Battle Royale. Discover the secret word before others in Portuguese, English, or Spanish.',
      'Point & Click com combate por turno. Pesque e batalhe contra os peixes do aquário.': 'Point & Click with turn-based combat. Fish and battle against the aquarium fish.',
      'Adventure game inspirado em Monkey Island. Sobreviva na floresta por 7 dias.': 'Adventure game inspired by Monkey Island. Survive in the forest for 7 days.',
      'Puzzle game. Converta animais em criaturas da noite sem ser pego.': 'Puzzle game. Turn animals into creatures of the night without getting caught.',
      'Coleção de jogos clássicos no terminal com ncurses em C.': 'Collection of classic games in the terminal with ncurses in C.',
      'Seu acervo definitivo de jogos indie brasileiro — 100% Open Source.': 'Your definitive Brazilian indie game collection — 100% Open Source.',
      'JOGOS QUE EU FIZ': 'GAMES I MADE',
      'GITHUB': 'GITHUB',
      'LINKEDIN': 'LINKEDIN',
      'INSTAGRAM': 'INSTAGRAM',
      'TWITTER / X': 'TWITTER / X',
      'YOUTUBE': 'YOUTUBE',
      'TWITCH': 'TWITCH',
      'ITCH.IO': 'ITCH.IO',
      'STEAM': 'STEAM',
      'AINDA TÔ ESCREVENDO MEUS PRIMEIROS ARTIGOS': "I'M STILL WRITING MY FIRST ARTICLES",
      'AGUENTA AÍ QUE LOGO LOGO SAI TEXTO BOM': "HANG IN THERE, GOOD TEXT IS COMING SOON",
      'FEITO COM CAOS E CARINHO': 'MADE WITH CHAOS AND CARE',
      '// FEITO COM CAOS E CARINHO': '// MADE WITH CHAOS AND CARE',
      '"vivendo a vida da maneira que eu quero viver"': '"living life the way I want to live it"',
      '// SOBRE MIM': '// ABOUT ME',
      '// SKILLS / STACK': '// SKILLS / STACK',
      '// PROJETOS OPEN SOURCE': '// OPEN SOURCE PROJECTS',
      '// JOGOS QUE EU FIZ': '// GAMES I MADE',
      '// GALERIA': '// GALLERY',
      '// BLOG': '// BLOG',
      '// CONTATO': '// CONTACT',
      '// SKILL': '// SKILL',
      '★ SHIVA ★': '★ SHIVA ★',
      '🏆 // RANKINGS': '🏆 // RANKINGS',
      'PEU BORGES': 'PEU BORGES',
      'ENG. DA COMPUTAÇÃO // DEV // CRIADOR DE JOGOS': 'COMPUTER ENG. // DEV // GAME CREATOR',
      'vivendo a vida da maneira que eu quero viver': 'living life the way I want to live it',
      'VER TODOS NO GITHUB': 'VIEW ALL ON GITHUB',
      'VER NO ITCH.IO': 'VIEW ON ITCH.IO',
      'SKILL': 'SKILL',
      'PROFICIÊNCIA': 'PROFICIENCY',
      'TETRIS': 'TETRIS',
      'FILMES': 'MOVIES',
      'SÉRIES': 'SERIES',
      'MÚSICAS': 'MUSIC',
      'CARREGANDO...': 'LOADING...',
      'MINHA PLAYLIST': 'MY PLAYLIST',
      'NENHUMA MÚSICA': 'NO MUSIC',
      'BIBLIOTECA MUSICAL': 'MUSIC LIBRARY',
      'FECHAR': 'CLOSE',
      'VOLUME': 'VOLUME',
      'ANTERIOR': 'PREVIOUS',
      'REINICIAR': 'RESTART',
      'PLAY/PAUSE': 'PLAY/PAUSE',
      'PARAR': 'STOP',
      'PRÓXIMA': 'NEXT',
      'VELOCIDADE': 'SPEED',
      'CONTA': 'ACCOUNT',
      'VOCÊ': 'YOU',
      'SEU RECORDE': 'YOUR RECORD',
      'ORDENADO POR SCORE': 'SORTED BY SCORE',
      'ORDENADO POR AVALIAÇÃO PESSOAL': 'SORTED BY PERSONAL RATING',
      'NENHUM ITEM AINDA': 'NO ITEMS YET',
      'LINES': 'LINES',
      'LEVEL': 'LEVEL',
      'OUÇA': 'LISTEN',
      'OPEN SPOTIFY': '▶ OPEN SPOTIFY',
      'SINOPSE': 'SYNOPSIS',
      'MINHA OPINIÃO': 'MY REVIEW',
      'EPISÓDIO FAVORITO': 'FAVORITE EPISODE',
      'MODO RETRO': 'RETRO MODE',
      '← → MOVER': '← → MOVE',
      '↑ ROTAR': '↑ ROTATE',
      '↓ DESCER': '↓ DOWN',
      'SPACE SOLTAR': 'SPACE DROP',
      'P PAUSA': 'P PAUSE',
      'ENTER REINICIAR': 'ENTER RESTART',
      'GAME OVER': 'GAME OVER',
      'PRESSIONE ENTER': 'PRESS ENTER',
      'PAUSA': 'PAUSE',
      '// KONAMI ACTIVATED': '// KONAMI ACTIVATED',
      'ATIVAR MODO NOTURNO': 'ENABLE NIGHT MODE',
      'ATIVAR MODO PROFISSIONAL': 'ENABLE PROFESSIONAL MODE',
      'IDIOMA': 'LANGUAGE',
      'NOTIFICAÇÕES': 'NOTIFICATIONS',
      'MOSTRAR': 'SHOW',
      'OCULTAR': 'HIDE',
      'MODO PROFISSIONAL': 'PROFESSIONAL MODE',
      'ATIVAR': 'ACTIVATE',
      'CONQUISTA DESBLOQUEADA!': 'ACHIEVEMENT UNLOCKED!',
      'INICIANTE': 'BEGINNER',
      'INTERMEDIÁRIO': 'INTERMEDIATE',
      'AVANÇADO': 'ADVANCED',
      'EXPERT': 'EXPERT',
      'ANOS': 'YEARS OLD',
      'SALVADOR, BA': 'SALVADOR, BA',
      '// MEU CONTROLE FAVORITO': '// MY FAVORITE CONTROLLER',
      'Cima': 'Up',
      'Esquerda': 'Left',
      'Direita': 'Right',
      'Baixo': 'Down',
      'Select': 'Select',
      'Start': 'Start',
      'Botao B': 'B Button',
      'Botao A': 'A Button',
      'SHIVA': 'SHIVA',
      'CARINHO': 'PET',
      'GOLDEN RETRIEVER, A COISA MAIS FOFA DESSE MUNDO, MINHA PARCEIRA DE CÓDIGO': 'GOLDEN RETRIEVER, THE CUTEST THING IN THIS WORLD, MY CODING BUDDY',
      'escreve pra shiva...': 'write to shiva...',
      'ENVIAR': 'SEND',
      'AU!! MANDA VER AÍ!! :D': 'WOOF!! LETS GO!! :D',
      'escrevendo... 🐾': 'typing... 🐾',
      'LINGUAGENS': 'LANGUAGES',
      'FERRAMENTAS': 'TOOLS',
      'VIDA': 'LIFE',
      '// MINHA PLAYLIST': '// MY PLAYLIST',
      'MUSICAS DE JOGOS QUE EU GOSTO': 'GAME MUSIC I LIKE',
      'OUTRAS MUSICAS': 'OTHER MUSIC',
      'ADICIONE ARQUIVOS .MP3 EM<br/><strong>ASSETS/SOUND/PLAYLIST/</strong>': 'ADD .MP3 FILES IN<br/><strong>ASSETS/SOUND/PLAYLIST/</strong>',
      'ERRO': 'ERROR',
      'MODO — PROFISSIONAL': 'PROFESSIONAL — MODE',
      'CONFIGURAR': 'CONFIGURE',
      'EXPORTAR PDF': 'EXPORT PDF',
      'DESATIVAR': 'DISABLE',
      'Ocultar barra': 'Hide bar',
      'Mostrar barra': 'Show bar',
      'TEMA': 'THEME',
      'PRESETS': 'PRESETS',
      'TIPOGRAFIA': 'TYPOGRAPHY',
      'CABEÇALHO': 'HEADER',
      'LAYOUT': 'LAYOUT',
      'CONTEÚDO': 'CONTENT',
      'PDF': 'PDF',
      'SALVAR': 'SAVE',
      'COMPARTILHAR': 'SHARE',
      'PADRÃO': 'DEFAULT',
      'SOBRE O MODO PROFISSIONAL': 'ABOUT PROFESSIONAL MODE',

      // Professional config labels
      'CORES PERSONALIZADAS': 'CUSTOM COLORS',
      'IMAGEM DE FUNDO': 'BACKGROUND IMAGE',
      'PADRÃO DE FUNDO': 'BACKGROUND PATTERN',
      'OPACIDADE DO PADRÃO': 'PATTERN OPACITY',
      'ANIMAÇÕES': 'ANIMATIONS',
      'PRESETS RÁPIDOS': 'QUICK PRESETS',
      'FAMÍLIA DA FONTE': 'FONT FAMILY',
      'TAMANHO DA FONTE': 'FONT SIZE',
      'TAMANHO DO TÍTULO PRINCIPAL': 'MAIN TITLE SIZE',
      'TAMANHO DOS TÍTULOS DE SEÇÃO': 'SECTION TITLE SIZE',
      'PESO DA FONTE': 'FONT WEIGHT',
      'ESPAÇAMENTO ENTRE PARÁGRAFOS': 'PARAGRAPH SPACING',
      'ALTURA DA LINHA': 'LINE HEIGHT',
      'ESPAÇAMENTO ENTRE LETRAS': 'LETTER SPACING',
      'ALINHAMENTO DO TEXTO': 'TEXT ALIGNMENT',
      'ALINHAMENTO DO CABEÇALHO': 'HEADER ALIGNMENT',
      'MOSTRAR LOCALIZAÇÃO': 'SHOW LOCATION',
      'MOSTRAR TÍTULO/CARGO': 'SHOW TITLE',
      'MOSTRAR LINKS DE CONTATO': 'SHOW CONTACT LINKS',
      'IMAGEM DE PERFIL': 'PROFILE IMAGE',
      'TAMANHO DA IMAGEM DE PERFIL': 'PROFILE IMAGE SIZE',
      'LARGURA DO CONTEÚDO': 'CONTENT WIDTH',
      'ESPAÇAMENTO ENTRE SEÇÕES': 'SECTION SPACING',
      'ESPAÇAMENTO ENTRE ITENS': 'ITEM SPACING',
      'PADDING DO CONTEÚDO': 'CONTENT PADDING',
      'ESTILO DO CABEÇALHO': 'HEADER STYLE',
      'LAYOUT DAS HABILIDADES': 'SKILLS LAYOUT',
      'LAYOUT DOS PROJETOS': 'PROJECTS LAYOUT',
      'ESTILO DOS BOTÕES': 'BUTTON STYLE',
      'ESTILO DAS LISTAS': 'LIST STYLE',
      'BORDA ARREDONDADA': 'BORDER RADIUS',
      'SOMBRA': 'SHADOW',
      'FUNDO ALTERNADO NAS SEÇÕES': 'ALTERNATE SECTION BG',
      'COR DO FUNDO DA SEÇÃO': 'SECTION BG COLOR',
      'MOSTRAR BORDAS': 'SHOW BORDERS',
      'MOSTRAR DIVISORES': 'SHOW DIVIDERS',
      'MOSTRAR BARRA DO TOPO': 'SHOW TOPBAR',
      'MOSTRAR RODAPÉ': 'SHOW FOOTER',
      'MOSTRAR PORCENTAGEM NAS HABILIDADES': 'SHOW SKILL PERCENTAGES',
      'NOME': 'NAME',
      'TÍTULO / CARGO': 'TITLE / ROLE',
      'LOCALIZAÇÃO': 'LOCATION',
      'SOBRE': 'ABOUT',
      'EMAIL': 'EMAIL',
      'GITHUB (usuário ou URL)': 'GITHUB (username or URL)',
      'LINKEDIN (URL)': 'LINKEDIN (URL)',
      'EXPERIÊNCIA': 'EXPERIENCE',
      'FORMAÇÃO': 'EDUCATION',
      'HABILIDADES': 'SKILLS',
      'PROJETOS': 'PROJECTS',
      'SEÇÕES PERSONALIZADAS': 'CUSTOM SECTIONS',
      '+ ADICIONAR SEÇÃO': '+ ADD SECTION',
      'INCLUIR NO PDF': 'INCLUDE IN PDF',
      'MARGENS': 'MARGINS',
      'TAMANHO DA FONTE NO PDF': 'PDF FONT SIZE',
      'TAMANHO DA PÁGINA': 'PAGE SIZE',
      'CORES NO PDF': 'PDF COLORS',
      'INCLUIR TOPO NO PDF': 'INCLUDE TOPBAR IN PDF',
      'Cargo': 'Role',
      'Empresa': 'Company',
      'Data': 'Date',
      'Descrição': 'Description',
      'Curso': 'Course',
      'Instituição': 'Institution',
      'Linguagem': 'Language',
      'URL': 'URL',
      'Conteúdo': 'Content',
      'Nova Seção': 'New Section',
      'Seção personalizada': 'Custom section',
      'Remover seção': 'Remove section',
      'Título': 'Title',
      'Nome': 'Name',
      'Título da seção': 'Section title',
      'Escreva aqui o conteúdo da seção...': 'Write the section content here...',
      'Erro ao gerar link': 'Error generating link',
      'Link copiado! Envie para qualquer pessoa.': 'Link copied! Send it to anyone.',
      'Erro ao copiar. Link: ': 'Error copying. Link: ',
      'Profissional': 'Professional',
      'Minimal': 'Minimal',
      'Escuro': 'Dark',
      'Natureza': 'Nature',
      'Pôr do Sol': 'Sunset',
      'Sistema': 'System',
      'Serif': 'Serif',
      'Monoespaçada': 'Monospace',
      'Extra pequena': 'Extra Small',
      'Pequena': 'Small',
      'Normal': 'Normal',
      'Grande': 'Large',
      'Extra grande': 'Extra Large',
      'Pequeno': 'Small',
      'Leve': 'Light',
      'Negrito': 'Bold',
      'Compacto': 'Compact',
      'Espaçoso': 'Spacious',
      'Espaçado': 'Relaxed',
      'Estreito': 'Narrow',
      'Largo': 'Wide',
      'Justificado': 'Justified',
      'Fade In': 'Fade In',
      'Slide In': 'Slide In',
      'Sem animação': 'No animation',
      'Sim': 'Yes',
      'Não': 'No',
      'Centro': 'Center',
      'Nenhum': 'None',
      'Pontos': 'Dots',
      'Linhas': 'Lines',
      'Grade': 'Grid',
      'Médio': 'Medium',
      'Plano': 'Flat',
      'Contorno': 'Outline',
      'Pílula': 'Pill',
      'Simples': 'Plain',
      'Bullet': 'Bullet',
      'Ícone': 'Icon',
      'Estreita': 'Narrow',
      'Larga': 'Wide',
      'Cheia': 'Full',
      'Detalhado': 'Detailed',
      '2 Colunas': '2 Columns',
      '3 Colunas': '3 Columns',
      'Lista': 'List',
      'Nenhuma': 'None',
      'Suave': 'Light',
      'Forte': 'Strong',
      'Português': 'Portuguese',
      'English': 'English',
      'Carta': 'Letter',
      'Colorido': 'Colored',
      'Escala de cinza': 'Grayscale',
      'Cabeçalho': 'Header',
      'Sobre': 'About',
      'Experiência': 'Experience',
      'Formação': 'Education',
      'Habilidades': 'Skills',
      'Projetos': 'Projects',
      'Contato': 'Contact',
      '🎮 Jogos': '🎮 Gaming',
      '💼 Corporativo': '💼 Corporate',
      '📢 Marketing': '📢 Marketing',
      '💻 Programação': '💻 Programming',
      'Escuro com laranja neon. Perfeito para dev de jogos indie.': 'Dark with neon orange. Perfect for indie game devs.',
      'Sóbrio com acentos verde-água. Para publishers profissionais.': 'Sober with teal accents. For professional publishers.',
      'Colorido e vibrante. Para desenvolvedor de jogos mobile.': 'Colorful and vibrant. For mobile game developers.',
      'Agressivo e escuro. Ideal para perfil de jogador competitivo.': 'Aggressive and dark. Ideal for competitive gamers.',
      'Escuro com verde matrix. Portfólio de game dev.': 'Dark with matrix green. Game dev portfolio.',
      'Sóbrio, azul-marinho. Para cargos de liderança.': 'Sober, navy blue. For leadership roles.',
      'Moderno com azul vibrante. Para startups de tecnologia.': 'Modern with vibrant blue. For tech startups.',
      'Conservador, fontes serifadas. Para banco/consultoria financeira.': 'Conservative, serif fonts. For banking/finance.',
      'Clean, profissional, minimalista.': 'Clean, professional, minimalist.',
      'Profissional azul-escuro. Para vendas/parcerias B2B.': 'Professional dark blue. For B2B sales/partnerships.',
      'Cores ousadas e layout moderno. Para agências de publicidade.': 'Bold colors and modern layout. For ad agencies.',
      'Moderno e vibrante. Para profissionais de marketing digital.': 'Modern and vibrant. For digital marketing pros.',
      'Clean com toque trendy. Para gestor de redes sociais.': 'Clean with a trendy touch. For social media managers.',
      'Elegante e premium. Para branding e posicionamento.': 'Elegant and premium. For branding and positioning.',
      'Layout largo e moderno. Para criadores digitais.': 'Wide and modern layout. For digital creators.',
      'Dark mode com acentos azul. O clássico dev.': 'Dark mode with blue accents. The classic dev.',
      'Moderno e colorido. Para especialista em frontend.': 'Modern and colorful. For frontend specialists.',
      'Minimalista e funcional. Sem firulas, só código.': 'Minimalist and functional. No frills, just code.',
      'Escuro com vermelho/âmbar. Estilo terminal/console.': 'Dark with red/amber. Terminal/console style.',
      'Moderno e limpo. Para desenvolvedor iOS/Android.': 'Modern and clean. For iOS/Android developers.',
      'Clean com púrpura analítico. Para área de dados.': 'Clean with analytical purple. For data science.',
      'Verde-escuro estilo Git. Para contribuidor OSS.': 'Dark green Git style. For OSS contributors.',
      'Profissional e maduro. Para liderança técnica.': 'Professional and mature. For tech leadership.',

      // Achievement names/descriptions
      'EXPLORADOR DIGITAL': 'DIGITAL EXPLORER',
      'Você visitou sua primeira rede social pelo site!': 'You visited your first social media from the site!',
      'Clique nos ícones de rede social no início da página...': 'Click on the social media icons at the top of the page...',
      'SABEDORIA PIXEL': 'PIXEL WISDOM',
      'Você explorou as habilidades do Peu!': 'You explored Peu skills!',
      'Clique em alguma skill na seção STACK...': 'Click on any skill in the STACK section...',
      'PAUSA PRO CAFÉ': 'COFFEE BREAK',
      'Você ficou mais de 5 minutos no site!': 'You stayed more than 5 minutes on the site!',
      'Fique mais tempo explorando o site...': 'Spend more time exploring the site...',
      'MELOMANIA': 'MELOMANIA',
      'Você colocou uma música para tocar!': 'You played a song!',
      'Abra a biblioteca musical e escolha uma música...': 'Open the music library and pick a song...',
      'AU!': 'WOOF!',
      'Você mandou sua primeira mensagem pra Shiva!': 'You sent your first message to Shiva!',
      'Tente conversar com a Shiva no fim da página...': 'Try talking to Shiva at the bottom of the page...',
      'NOSTALGI-AÇÃO': 'NOSTALGI-ACTION',
      'Você apertou 10 vezes no controle NES!': 'You pressed the NES controller 10 times!',
      'Fique apertando os botões do controle NES...': 'Keep pressing the NES controller buttons...',
      'BLOCO CAIU': 'BLOCK DROPPED',
      'Você invocou o Tetris!': 'You summoned Tetris!',
      'Use o código Konami (↑↑↓↓←→←→ BA)': 'Use the Konami code (↑↑↓↓←→←→ BA)',
      'PASSEIO SOMBRIO': 'DARK WALK',
      'Você enfrentou o Terror de Shiva!': 'You faced the Terror of Shiva!',
      'Tente "passear" com a Shiva...': 'Try "walking" with Shiva...',
      'MELHOR AMIGO': 'BEST FRIEND',
      'Você mandou 100 mensagens pra Shiva! Ela te ama!': 'You sent 100 messages to Shiva! She loves you!',
      'Mande muuuuitas mensagens pra Shiva...': 'Send maaaany messages to Shiva...',
      'VICIADO EM TETRIS': 'TETRIS ADDICT',
      'Você fez 5.000+ pontos no Tetris!': 'You scored 5,000+ points in Tetris!',
      'Jogue Tetris até passar dos 5.000 pontos...': 'Play Tetris until you reach 5,000 points...',
      'SEM VIDA SOCIAL': 'NO SOCIAL LIFE',
      'Você passou mais de 2 horas no site!': 'You spent 2+ hours on the site!',
      'Deixe o site aberto por muito tempo...': 'Leave the site open for a long time...',
      'LENDA DO TETRIS': 'TETRIS LEGEND',
      'Você fez 15.000+ pontos no Tetris! Lendário!': 'You scored 15,000+ in Tetris! Legendary!',
      '15.000+ pontos no Tetris... só os deuses!': '15,000+ points in Tetris... only the gods!',

      // Doghouse
      'VOCÊ ESTÁ SENDO OBSERVADO': 'YOU ARE BEING WATCHED',
      '[ CLIQUE OU TECLE ENTER PARA CONTINUAR ]': '[ CLICK OR PRESS ENTER TO CONTINUE ]',
      '◀ VIRAR ▶': '◀ TURN ▶',
      '[ FECHAR — ESC ]': '[ CLOSE — ESC ]',
      '[ CLIQUE PARA VOLTAR ]': '[ CLICK TO RETURN ]',
      ' selecionado': ' selected',
      ' — pego.': ' — taken.',
      'Já tem isso.': 'Already have that.',
      'Não combina.': 'Does not combine.',
      'A vela acende. A sala se revela.': 'The candle lights up. The room is revealed.',
      'A chave está completa!': 'The key is complete!',
      'A grade range! Uma guia velha cai.': 'The grate creaks! An old leash falls.',
      'O espelho estilhaça! Um caco no chão.': 'The mirror shatters! A shard on the floor.',
      'Está escuro demais para ver direito.': 'Too dark to see properly.',
      'O tijolo se solta! Um fragmento de chave cai.': 'The brick comes loose! A key fragment falls.',
      'Água escura. Não dá pra ver o fundo.': 'Dark water. Cannot see the bottom.',
      ' não funciona na porta.': ' does not work on the door.',
      ' não quebra a grade.': ' does not break the grate.',
      'Já resolveu.': 'Already solved.',
      'Precisa de ': 'Need ',
      ' oferecido a Shiva.': ' offered to Shiva.',
      'Shiva aceitou as oferendas! Fragmento de chave e coleira caem do teto.': 'Shiva accepted the offerings! Key fragment and collar fall from ceiling.',
      'A gaveta está vazia.': 'The drawer is empty.',
      'O ralo está vazio.': 'The drain is empty.',
      'Pedra': 'Stone',
      'Caco de Vidro': 'Glass Shard',
      'Fósforo': 'Match',
      'Vela': 'Candle',
      'Vela Acesa': 'Lit Candle',
      'Corda': 'Rope',
      'Gancho': 'Hook',
      'Corda com Gancho': 'Rope with Hook',
      'Barra de Ferro': 'Iron Bar',
      'Fragmento de Chave I': 'Key Fragment I',
      'Fragmento de Chave II': 'Key Fragment II',
      'Fragmento de Chave III': 'Key Fragment III',
      'Dois Fragmentos': 'Two Fragments',
      'Chave Completa': 'Complete Key',
      'Guia': 'Leash',
      'Coleira': 'Collar',
      'Bola': 'Ball',
      'Osso': 'Bone',
      'Porta de madeira. Três fechaduras. Precisa de algo...': 'Wooden door. Three locks. Needs something...',
      'Madeira grossa, ferro, três fechaduras.': 'Thick wood, iron, three locks.',
      'Barras de ferro presas na parede.': 'Iron bars embedded in the wall.',
      'Pequena janela alta. Pouca luz entra.': 'Small high window. Little light enters.',
      'Não há resposta.': 'No response.',
      'A caixa range quando aberta. Vazia.': 'The box creaks when opened. Empty.',
      'Arranhões profundos na parede.': 'Deep scratches on the wall.',
      'Prateleira de madeira empoeirada.': 'Dusty wooden shelf.',
      'Espelho empoeirado. Mal reflete.': 'Dusty mirror. Barely reflects.',
      'Tecida no canto.': 'Woven in the corner.',
      'Escuro. Ecoa.': 'Dark. Echoes.',
      'Algo escrito na parede.': 'Something written on the wall.',
      'Água escura.': 'Dark water.',
      'Tábuas soltas no chão.': 'Loose floorboards.',
      'Goteira no teto.': 'Ceiling leak.',
      'Gaveta fechada.': 'Locked drawer.',
      'Diário empoeirado.': 'Dusty diary.',
      'Bancada de trabalho coberta de ferramentas.': 'Workbench covered in tools.',
      'Pedaço de corda pendurado.': 'Piece of rope hanging.',
      'Corrente grossa pendurada no teto.': 'Thick chain hanging from ceiling.',
      'Alçapão no teto. Trancado.': 'Ceiling trapdoor. Locked.',
      'GAVETA TRANCADA — TRÊS PINOS': 'LOCKED DRAWER — THREE PINS',
      'Clique na parte de cima...': 'Click on the top part...',
      'PINO ': 'PIN ',
    }
  }

  /* ----------------------------------------------------------
   *  getLang()  → retorna o código do idioma atual ('pt'|'en')
   * ---------------------------------------------------------- */
  function getLang() {
    return currentLang
  }

  /* ----------------------------------------------------------
   *  setLang(lang)
   *  Altera o idioma, persiste no localStorage, atualiza <html lang>,
   *  re-traduz a página e dispara evento 'langchange' para os módulos
   *  que precisam re-renderizar conteúdo dinâmico.
   * ---------------------------------------------------------- */
  function setLang(lang) {
    if (!dict[lang]) return
    currentLang = lang
    localStorage.setItem(LANG_KEY, lang)
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : 'en'
    translatePage()
    window.dispatchEvent(new CustomEvent('langchange', { detail: { lang: lang } }))
  }

  /* ----------------------------------------------------------
   *  __(key, fallback?)
   *  Função principal de tradução.
   *  - Busca a chave no idioma atual
   *  - Se não existir (ou for string vazia), busca em PT
   *  - Se não existir em lugar nenhum, retorna fallback || a própria chave
   * ---------------------------------------------------------- */
  function __(key, fallback) {
    if (!key && key !== '') return ''
    if (dict[currentLang] && dict[currentLang][key] !== undefined) {
      var val = dict[currentLang][key]
      if (val === '') return key
      return val
    }
    if (dict.pt[key] !== undefined) {
      return dict.pt[key]
    }
    return fallback || key
  }

  /* ----------------------------------------------------------
   *  translatePage()
   *  Varre o DOM em busca de elementos com atributos data-i18n-*
   *  e substitui o conteúdo/innerHTML/texto pelo traduzido.
   *
   *  Atributos suportados:
   *    data-i18n           → innerHTML (permite <strong>, <br/>)
   *    data-i18n-placeholder → placeholder
   *    data-i18n-title     → title
   *    data-i18n-aria      → aria-label
   *    data-i18n-meta      → content (meta tags)
   *
   *  IMPORTANTE: usa innerHTML, não textContent. Elementos com
   *  conteúdo dinâmico NÃO devem ter data-i18n.
   * ---------------------------------------------------------- */
  function translatePage() {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n')
      el.innerHTML = __(key)
    })
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder')
      el.placeholder = __(key)
    })
    document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-title')
      el.title = __(key)
    })
    document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-aria')
      el.setAttribute('aria-label', __(key))
    })
    document.querySelectorAll('[data-i18n-meta]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-meta')
      el.setAttribute('content', __(key))
    })
  }

  // Expõe as funções globalmente
  window.__ = __
  window.__lang = getLang
  window.__setLang = setLang

  // Auto-traduz ao carregar o DOM
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () {
      document.documentElement.lang = currentLang === 'pt' ? 'pt-BR' : 'en'
      translatePage()
    })
  } else {
    document.documentElement.lang = currentLang === 'pt' ? 'pt-BR' : 'en'
    translatePage()
  }

  // NOTA: Não há MutationObserver — elementos adicionados dinamicamente
  //       usam __() diretamente + escutam o evento 'langchange'.
})()






