(function () {
  var R = {
    happy: [
      'AU AU AU AU!! :D',
      'AU AU AU AU AU!! :D',
      'WOF WOF WOF!! :D',
      'AUUUUUU!! :D',
      'AU AU AU!! *abanando o rabo* :D',
      'AU AU!! *pula de alegria* :D',
      'AU! AU! AUUUU! :D',
      'WOOF WOOF!! :D',
      'AU AU AU AU!! *corre em circulos* :D',
      'AU AU!! *lambe a tela* :D',
      'AU!! *faz a festa* :D',
      'WOF!! *dancinha feliz* :D',
      'AU!! AU!! AU!! *gira que nem maluca* :D',
      'UUUUAU AU AU!! :D',
      'WOOOOF!! *te amo* :D',
      'AU!! *senta e da a pata* :D',
      'AU AU AUUU!! *muita felicidade* :D',
      '*abanando o rabo a mil por hora* AU!! :D',
      'AU!! *se joga no chao de tanta alegria* :D',
      'AU AU! *late sorrindo* :D',
      'QUE MAXIMO AU AU!! :D',
      'AU!! *te puxa pra brincar de tanta alegria* :D',
      'ESTOU TAO FELIZ AU!! :D',
      'AUAUAUAU!! *late sem parar* :D',
      '*da cambalhota* AU!! :D',
      'HOJE TA DIA DE FESTA AU!! :D',
      'AU!! *te molha de lambida* :D',
      '*senta e abana o rabo no chao* AU!! :D',
      'AU!! *corre e volta corre e volta* :D',
      'VOCE ME FAZ MUITO FELIZ AU!! :D',
      '*deita no seu colo e suspira feliz* auuu... :D',
      'AU AU AU!! *late no ritmo da felicidade* :D',
      'WOOOOF!! *te encara com olhos brilhando* :D',
      'AU!! *te chama pra festa* VEM VEM!! :D',
    ],
    sad: [
      'au... au... :(',
      'auuuuu... :(',
      '...au... *deita no seu colo* :(',
      'au... *encosta a cabeca* :\'(',
      'au... *lambe sua mao* :(',
      'au... au... *olhos tristes* :((',
      'au... *abana o rabo devagar* :I',
      'nao fica triste nao... au... *deita do seu lado* :(',
      'au... *coloca a pata no seu colo* :\'(',
      'au... :\'(',
      'au... *suspiro triste* ...au...',
      'vem ca... au... *deita do seu lado* :(',
      'au... *encosta o nariz gelado* :(',
      'au... *te olha com olhos de cachorro*... :(',
      'au. *sente sua falta* .au.',
      '*cabeca baixa* au...',
      'au... queria ajudar... :\'(',
      'au... *deita e coloca a cabeca na sua perna* :(',
      'nao... au... *abana triste* ...au...',
      'au... *te entende* :(',
      'au... *suspira e encosta em voce* ...:(',
      'vou ficar aqui do seu lado... au... :(',
      'au... *coloca a cabeca no seu colo e nao sai* :(',
      'as vezes a vida e assim... au... *lambe sua mao* :(',
      'mas eu to aqui... au... sempre... :(',
      'au... *te olha com olhos compreensivos* :(',
      'sabe o que melhora? carinho... au... :(',
      'vamos ficar de boa juntos... au... :(',
      'au... *se aconchega e nao te abandona* :(',
      'pode chorar... au... to aqui... :(',
      'eu sinto quando voce ta triste... au... :(',
      'au... *deita em cima do seu pe pra te aquecer* :(',
      'vai passar... au... *lambe suas lagrimas* :(',
    ],
    angry: [
      'AU AU AU!! >:(',
      'GRRR AU AU!! >:(',
      'AU!! AU!! >:(',
      'WOF WOF WOF!! >:(',
      'AU!! *rosna* >:(',
      'AU AU AU AU AU!! >:(',
      '*grrr* AU!! >:(',
      'HMPF AU!! >:(',
      'AU!! *vira de costas* >:(',
      'WOF!! *late bravo* >:(',
      'AU AU!! *rosna baixinho* >:(',
      'GRRR... AU!! >:(',
      'NAO GOSTEI!! AU!! >:(',
      'AU!! *bate a pata no chao* >:(',
      'WORF WORF!! >:(',
      '*pelo do lombo ericado* AU!! >:(',
      'AU!! AU!! AU!! *toda estressada* >:(',
      'HMPF!! *sai andando* >:(',
      'AU... NAO!! AU!! >:(',
      'GRRRRR... *mostra os dentes de brincadeira* AU!! >:(',
      'ISSO ME DEIXA BRAVA AU!! >:(',
      'AU!! *rosna pro mundo* >:(',
      'QUE SACO AU!! >:(',
      'nao me venha com essa... AU!! >:(',
      'AU!! *late e late sem parar* >:(',
      'QUERO NAO AU!! >:(',
      '*grrr* ...AU!! ...*grrr* ...AU!! >:(',
      'VOU IGNORAR VOCE AU!! >:(',
      '*cara feia canina* au. >:(',
      'AU!! *rosna baixinho e se afasta* >:(',
      'HOJE NAO TA DIA NAO AU!! >:(',
      'pode ficar brava tambem... AU!! >:(',
      'AU! (esse lateu serio) >:(',
    ],
    love: [
      'au... au... *deita no seu colo* <3',
      'AU AU!! <3',
      'auuuuu ♥ *abanando o rabo* <3',
      '*lambe seu rosto* AU AU <3',
      'au ♥ au ♥ au ♥',
      'AU!! *se joga no seu colo* <3',
      'au... *coloca a cabeca no seu colo* <3',
      '*deita de barriga pra cima* au... <3',
      'au au ♥ *segue voce pela casa* <3',
      'AU AU AU AU TE AMO AU AU!! <3',
      'au... <3 *te lambe* ...au <3',
      '*enconsta o nariz gelado em voce* au♥',
      'au♥ au♥ au♥ *late amor*',
      'MUUUITO AMOR AU!! <3',
      'au... *se enrosca em voce* <3',
      '♥ AU ♥ AU ♥ AU ♥',
      '*deita no seu pe* au... te amo... <3',
      'au!! *coloca a cabeca no seu colo e suspira feliz* <3',
      'voce e tudibom au!! <3',
      'AU!! *te lambidas e carinho* <3',
      'au... meu humano favorito... <3',
      'AU!! ♥ AU!! ♥ AU!! ♥',
      'te amo em 20 linguas diferentes... au! <3',
      '*se derrete toda* auuuu... <3',
      'AUHHH ♥ *late com amor*',
      'voce e a razao do meu abanar de rabo <3',
      'au♥ vou te amar pra sempre au♥',
      'nunca vou esquecer de voce... au... <3',
      'AU!! *te protege com a pata* <3',
      'meu lugar favorito e perto de voce au♥',
      'AU!! *te abraça com as patas* <3',
      'quando voce ta perto tudo fica bem au♥',
    ],
    food: [
      'AU AU AU AU AU!! COMIDA!! :D',
      'AUUUUUUUUU!! PETISCO!! :D',
      'AU!! *saliva* ONDE?? :D',
      'AU! AU! AU! *roda em circulo* :D',
      'WOF WOF!! QUERO!! :D',
      'AU!! *senta bonitinho* :D',
      'AU! *da a pata* :D',
      'AUUU... *encara o pote*... AU!! :D',
      'AU AU AU!! SNACKS!! :D',
      '*orelha em pe* AU?? COMIDA?? AU!! :D',
      'AU!! *babando* :D',
      'AGORA?? AU AU!! AGORA?? :D',
      '*salivando* ...au... AU AU AU!! :D',
      'AU!! *te leva ate a cozinha* :D',
      'AU AU AU!! HORARIO DO PETISCO!! :D',
      'WOF!! *senta e treme de ansiedade* :D',
      'AU!! DA UMA PROVINHA AI!! :D',
      'AUU... *te encarando* ...AUU... :D',
      '*fareja o ar* AU!! SENTI!! :D',
      'AU!! *gira que nem um tornado* COMIDA!! :D',
      'COMIDA?? ONDE?? QUERO?? AGORA!! :D',
      'AU AU AU!! *te guia ate a cozinha* :D',
      'HUMMMM QUE CHEIRO BOM AU!! :D',
      'AU!! *fica de guarda perto do pote* :D',
      'PETISCOOOO AU AU AU AU!! :D',
      '*se contando de ansiedade* AU!! :D',
      'WOF!! *lambe os beiços* :D',
      'AU!! *te encara com olhos de fome* :D',
      'AU AU!! ABRE LOGO!! :D',
      'AU *pula* AU *pula* AU *pula* :D',
      'TO PRONTA PRA REFEICAO AU!! :D',
      'COMIDA E AMOR AU!! :D',
      'AU!! *traz o pote vazio na boca* :D',
    ],
    play: [
      'AU AU AU AU!! PASSEAR!! :D',
      'AU!! *pega a coleira* :D',
      'WOF WOF!! VAMOS!! :D',
      'AU AU!! *corre pra porta* :D',
      'AU!! *pula de ansiedade* :D',
      'AU AU AU!! BOLA!! :D',
      'WOF!! *traz o brinquedo* :D',
      'AU!!! *nao para quieto* :D',
      'AU AU!! *faz a festa* :D',
      'AU!! *giro 360 de empolgacao* :D',
      'BORA BORA BORA AU AU!! :D',
      'AU!! *te empurra o brinquedo na mao* :D',
      'WOF!! *agacha e faz graca* :D',
      'AU AU AU!! *late de ansiedade boa* :D',
      '*pega a bolinha e solta no seu pe* AU!!',
      'VAMOS BRINCAR AU AU!! :D',
      'AU!! *corre em circulos na sua volta* :D',
      '*te encara com a bolinha na boca* hmmm... au!!',
      'AU AU!! *nao para quieta um segundo* :D',
      'WOF!! *te convida pra brincar* VEM!! :D',
      '*derruba o brinquedo no seu colo* AU!! :D',
      'AU!! *late e corre em zig zag* :D',
      'TO AQUI VEM BRINCAR AU!! :D',
      '*te cutuca com o focinho* ...agora!! AU!! :D',
      'AU AU AU!! *da a volta em voce* :D',
      'BATE BATE BATE AU AU!! :D',
      '*late e late ate voce se levantar* AU!! :D',
      'AGORA?? TA NA HORA?? AU!! :D',
      '*te observa com o brinquedo na boca* ...AU!! :D',
      'AU AU!! *joga a bolinha pra voce pegar* :D',
      'CANSADA? EU NUNCA!! AU AU!! :D',
      'MAIS UMA RODADA AU!! :D',
    ],
    sleepy: [
      'au... *boceja* zzz...',
      'au... *deita e dorme* zzz',
      'auuu... *olhos pesados* zzz...',
      '...au... *ja dormindo* zzz',
      'au... *se enrosca* zzz...',
      'zuau... *dormindo* zzz...',
      'au... *sonha e mexe as patas* ...au ...au...',
      'zzz... au... zzz...',
      'au... *cabeca caindo de sono* zzz...',
      '*bocejo canino* asuuunn... *dorme* zzz',
      'hmm... au... *fecha os olhos* zzz...',
      '*ronca baixinho* ...au... zzz',
      'au... to com sono... *se aninha* zzz',
      'zzz au zzz au zzz... *sonhando com os anjinhos*',
      'au... *cobre o nariz com a pata* zzz...',
      'nao quero dormir... au... *ja dormindo* zzz',
      '*suspira* ...au... *pega no sono* zzz',
      'au... ta na hora de dormir sim... zzz...',
      'zzZZzz... *acorda* au? *dorme de novo* zzz',
      'au (bocejo) ...au (bocejo denovo) ...au (dormi) zzz',
      'au... *deita no seu colo e apaga* zzz',
      'que sono... au... *se espreguica* zzz',
      '*bocejo gigante* AU... queria dizer... au... zzz',
      'au... to numa preguiça... zzz...',
      'melhor lugar do mundo: sua cama... au... zzz',
      'zzZzz *fim de tarde* au... zZzzz',
      'depois de brincar... au... *ja era* zzz',
      'au...*comida*...au...*sonho*...au...*ambos* zzz',
      'nao mexe em mim que eu to tao gostosa... zzz',
      'au... *dormindo com a cabeca no travesseiro* zzzzz',
      'ate meus roncos sao fofos... au... zzz',
      'au... *se estica todo* ...zuuau... zzz',
    ],
    curious: [
      'au?? *inclina a cabeca*',
      'AU??',
      'au au?? *pisca*',
      'au? au? *fareja o ar*',
      'WOF?? *cabeca inclinada*',
      'au? *orelha em pe*',
      'au...?? *confusa*',
      'AU?? AU?? *late perguntando*',
      'au... *pensa* ...AU??',
      'au au au?? *tenta entender*',
      'hmm?? au?? *inclina a cabeca dos dois lados*',
      'AU? *pisca lentamente*',
      'au... *te olhando de cabeca torta*',
      'pera... au?? *processando*',
      '*inclina a cabeca 45 graus* au...??',
      'AU?? NAO ENTENDI!! AU!!',
      'au... au... *pensa pensa* ...au!!',
      'seii laaa au?? *da de ombros canina*',
      'au... explica de novo... *cabeca inclinada*',
      'o que que isso? au? *fareja*',
      '*cabeca inclinada 90 graus* AU??!!',
      'nao to entendendo nada... au... *pisca*',
      'AU?? voce ta falando serio?? :O',
      'au... au... *tenta processar a informacao*',
      'hm?? au?? *orelha vai e volta*',
      'oque que e isso? posso comer? au??',
      'AU?? AU?? *late em modo interrogatorio*',
      '*te olha de lado* auuu...?? *esperando*',
      'perai... deixa eu cheirar... *fareja* ...au!',
      'isso e novo... au?? *estranha mas curiosa*',
      'explica denovo com mais calma... au??',
      'agora eu nao sei se e brincadeira ou verdade au??',
    ],
    greeting: [
      'AU AU!! BEM VINDO!! :D',
      'AU!! *recebe na porta* :D',
      'WOF WOF!! OI!! :D',
      'AU AU AU!! *abanando o rabo* :D',
      'AU!! QUE BOM TE VER!! :D',
      'AU AU!! *cheira voce* :D',
      'AUUUU!! *festa* :D',
      'WOF!! *da a volta em circulos* :D',
      'AU!! *encosta o nariz* :D',
      'AU AU AU AU!! *muita emocao* :D',
      'OI OI OI AU!! :D',
      'SALVE SALVE AU!! :D',
      'AU!! *pula de alegria* :D',
      'FALA AMIGO AU!! :D',
      'AUU AUU!! QUE SAUDADE!! :D',
      '*te cheira inteira* AU!! :D',
      'AAAAAUUUUUU!! :D',
      'WOF!! *te cumprimenta com a patinha* :D',
      'AU!! E NOIS!! :D',
      'AUAUAUAUAUAUAUU!! *emocionada demais* :D',
      'CHEGOU!! FINALMENTE AU!! :D',
      'AU!! *te rodeia de felicidade* :D',
      'JA ESTAVA SENTINDO SUA FALTA AU!! :D',
      'OIIII AU AU AU AU!! :D',
      '*abanando o rabo que venta na sala* AU!! :D',
      'QUE BOM QUE VOCE VEIO AU!! :D',
      'AU!! *cumprimenta como se nao te visse ha anos* :D',
      '*cheira seu pe e faz festa* AU!! :D',
      'WOF!! WOF!! *te recebe com musica canina* :D',
      'AAAAAH CHEGOU MINHA PESSOA FAVORITA AU!! :D',
      'AU! AU! *festa de boas vindas* :D',
      '*late bem-vindo* AU-u AU-u AU-u!! :D',
    ],
    goodbye: [
      'au... ja vai? :(',
      'au... *triste por voce ir* :(',
      'AU AU!! VOLTA LOGO!! :D',
      'au... *acena com a pata* tchau...',
      'au... *deita na sua cama sentindo falta* :(',
      'AU!! ATE MAIS!! :D',
      'AU AU!! NAO ESQUECE DE VOLTAR!! :D',
      'WOF WOF!! FOI UM PRAZER!! :D',
      'au... *late baixinho* volta logo...',
      'tchau amigo... au... *abanando triste* :(',
      'AU!! FOI OTIMO TE VER!! VOLTA LOGO!! :D',
      'au... *te ve indo* ...au... :(',
      'nao vai nao... au... :\'(',
      'ATE MAIS AU!! *pisca* :D',
      'au... *promete que volta?* :(',
      'AU AU!! *corre ate o portao* :D',
      'WOF!! FOI DIVERTIDO!! :D',
      'au... *fica olhando de longe* ...au... :(',
      'VOLTA SEMPRE AU!! :D',
      'tchau... au... :\'( (vou sentir saudades)',
      'au... *late um tchauzinho* :(',
      'AU!! *late alto* NAO VAI!! :(',
      'au... *se deita na porta* ...nao vai...',
      'ja? au... *olhos tristes* mas acabou de chegar...',
      'AU!! TRAZ UM PETISCO QUANDO VOLTAR!! :D',
      'au... *suspira* vou ficar te esperando... :(',
      'VOLTA LOGO QUE EU VOU ESTAR AQUI AU!! :D',
      'nao demora... au... *cara de cachorro triste* :(',
      'AU!! ATE A PROXIMA AVENTURA!! :D',
      '*te ve indo e da um uivo baixinho* auuuuu... :(',
      'leva eu junto... au... *olhar pidao* :(',
      'tchau... vou sentir sua falta... au... :\'( u.u',
    ],
    sassy: [
      'humpf... au.',
      'au. (so um au mesmo)',
      '....au.....(demorou pra responder hein)',
      'AU. (ponto.)',
      '*olha com desprezo* ...au.',
      'au... *viro a cara*',
      'HMPF.',
      'au. *abanou uma vez so*',
      '......au.',
      '*suspira* au.',
      'aham... au. *ironia canina*',
      'au. (com desdem)',
      'la ele au... *pisca*',
      'au. *te ignora*',
      'hmm.... *te olha de canto* au.',
      'sei... au. *cara de deboche*',
      'au. (e dai?)',
      'blz... au. *virada de bunda*',
      'au. au. *cada au uma verdade*',
      'fala serio... au. *cara de paisagem*',
      'poderia ter falado isso antes... au.',
      'AU. *late e sai de fininho*',
      'confia... au.',
      'cara... au. *te julgando*',
      'au. (silencio constrangedor)',
      'ah ta... au. *entendi nada mas blz*',
      'partiu... au. *vai deitar de costas*',
      'mhm... au. *abanou uma orelha so*',
      'aff... au. *deitou de proposito longe*',
      'sabia que eu sou mais legal que isso? au.',
      'po... au. *te encarando com um olho aberto*',
    ],
    silly: [
      'AU AU AU AU AU AU AU AU AU',
      'WOFAUFAUFAUF WOF WOF!! :D',
      'au. nao. au. AU!',
      'AU! ...au? ...AU!!',
      'au (em portugues) au (em ingles) AU (BERRO)',
      'AUFAUFAUFAUFAUF!! :D',
      '*late em codigo morse* .--. . --. .-',
      'au... pera... vou pensar... AU!!',
      'au-WIFI au-BLUETOOTH au-MODERNO',
      'AU! AU! ...(eco)... AU! AU!',
      'AU! te-amo AU! te-amo AU! (traducao)',
      '*late em 8 idiomas* WOOF AU WAF BOW WOW GUAU',
      'au? na verdade... AU!! AFAUFAUF!!',
      'AU. AU. AU. (musica classica canina)',
      '*bug canino* au... au... AU.... *travou*',
      'AU (em caps lock) au (em minusculo) Au (com vergonha)',
      'AUF! AUF! *latido premium* AUF!',
      '*late em stereo* AU...AU...AU...',
      'fun fact: au ao contrario e ua. e ua ao contrario e au.',
      'AU? AU!! AU? AU!! *so subindo e descendo tom*',
      'AU! *late e se assusta com o proprio latido*',
      '*late pra propria sombra* AU!! AU!! ...ah, era eu.',
      'au (vertical) au (horizontal) au (diagonal)',
      'AU!! HACKERAM MEU SISTEMA DE LATIDOS!! :D',
      'au em hex: 0x61 0x75. AU em hex: 0x41 0x55.',
      '*late em latim* CANIS CANIS!',
      'se eu fosse um peixe eu faria glow? au?',
      '*late e esquece o que ia falar* ...au.',
      'AU! (isso foi um teste de microfone)',
      'a u (espacado) a...u... (bem lento) AU!! (rapido)',
    ],
    treat: [
      'AUUUUUU!! PETISCO!! PETISCO!! :D',
      'AU AU AU!! BISCOITO!! :D',
      'AU!! *cheira o bolso* :D',
      'WOF!! *sabia que era petisco* :D',
      'AU AU!! *faz truque* :D',
      'AUUU... *implora com os olhos* :D',
      '*orelha em pe* AU? OUVIU PETISCO? AU!! :D',
      'AU!! *te segue ate a despensa* :D',
      'AU AU AU!! OSSINHO!! :D',
      'PETISCO PETISCO PETISCO AU AU!! :D',
      '*da a pata* *da a outra* *roda* *deita* AU!! MERECI!! :D',
      'AU!! *se joga no chao de costas* :D',
      '*olhar de cachorro de comercial de racao* ...au... :D',
      'AU!! *trava no modo petisco* :D',
      'WOF!! ACHO QUE OUVIR A PALAVRA MAGICA!! :D',
      'AU!! QUAL SABOR?? :D',
      'AU AU AU!! NAO VAI ME DEIXAR NA MAO!! :D',
      'AU! AU! *late em ritmo de "quero quero"* :D',
      'AUUU... *derretendo de ansiedade* :D',
      'SO DE VOCE PENSAR EM PETISCO EU JA SEI AU!! :D',
      'AU!! *faz o maior escandalo por um petisco* :D',
      'WOF!! *te encarando* ja que vai dar... da logo!! :D',
      'AU!! *senta e treme que nem folha* :D',
      'PETISCO DETECTADO AU!! :D',
      'AU!! AGORA?? POSSO?? SIM?? :D',
      '*hackeia o sistema com olhar pidao* au... :D',
      'AU AU AU!! EU SEI O QUE E ISSO!! :D',
      '*fareja o pacote* AU!! E O MEU FAVORITO!! :D',
      'AU!! *te leva ate o armario dos petiscos* :D',
      'WOF WOF!! VOCE E O MELHOR HUMANO DO MUNDO!! :D',
    ],
    compliment: [
      'AU!! *corcoveia de alegria* :D',
      'AU AU AU!! SOU LINDA MESMO!! :D',
      '*abanando o rabo loucamente* AU!! :D',
      'AU!! *se arruma toda* :D',
      'WOF!! OBRIGADA!! :D',
      'AU AU!! *pisca um olho* :D',
      'seii... au... *modesta* :D',
      'AU AU!! SUA LINDO TAMBEM!! :D',
      '*deita de costa pra ganhar carinho na barriga* AU!!',
      'AU!! *lambe o elogio* :D',
      'AU!! FICO ATE SEM JEITO!! :D',
      '*corre e volta com um brinquedo* AU!! OBRIGADA!! :D',
      'AU... *corou* (cachorro cora?) :D',
      'AU!! *abanando o rabo que vira helice de helicoptero* :D',
      'hihi au!! *sorriso canino* :D',
      'sei que sou... au... ♥',
      'AU!! *da um beijinho* :D',
      'AU AU!! FALOU TUDO!! :D',
      'AU... *te olha com carinho* obrigada :D',
      'AU!! FICO ATRAPALHADA DE TANTA ALEGRIA!! :D',
      'AU!! *se produz toda* PRONTA!! :D',
      'fala mais... au... *presta atencao* :D',
      'AU!! *abanando o rabo sem parar* :D',
      'ELOGIO E SEMPRE BEM VINDO AU!! :D',
      '*da uma rodadinha* AU!! GOSTOU?? :D',
      'AU!! *late feliz* VOCE TAMBEM E!! :D',
      'hmm sei... au... *modesta mas adorando* :D',
      'AU!! *te lambe o rosto de gratidao* :D',
      'posso ate ser linda mas voce e mais... AU!! :D',
      '*se estica toda* AU!! OBRIGADA MESMO!! :D',
    ],
    music: [
      'AU AU AU AU!! QUE MUSICA BOA!! :D',
      '*uiva junto* AUUUUUUUU... :D',
      'AU!! *bate a pata no ritmo* :D',
      'WOF WOF!! *dancando* :D',
      'AU AU!! ESSA MUSICA E MINHA FAVORITA!! :D',
      '*cabeca inclinada* ouvindo... au... que lindo...',
      'AU!! *late no tom da musica* :D',
      'essa e braba AU AU!! :D',
      'AU!! *fecha os olhos e aprecia* :D',
      'WOF!! AUMENTA O SOM!! :D',
      '*uivo canino* AUUUUUUUUUUUUU... :D',
      'AU AU!! ROCK AND ROLL!! :D',
      'au... musica classica... que paz... zzz...',
      'AU!! *tenta dancar mas atrapalha tudo* :D',
      'isso me faz querer correr AU AU!! :D',
      'AU!! *late junto com a batida* :D',
      'que som gostoso... au... *relaxa*',
      'WOF!! *canta junto desafinado* :D',
      'AU!! *te puxa pra dancar* :D',
      'essa musica me lembra voce... au... <3',
    ],
    water: [
      'AU AU AU!! AGUA FRESCA!! :D',
      '*bebe agua feliz* au... glub glub... AU!! :D',
      'AU!! BANHO?? BANHO?? :D',
      'WOF!! *pula na agua* :D',
      'AU AU!! PISCINA!! :D',
      '*se sacode* AU!! MOLHADA!! :D',
      'AU!! *enfia a cabeca na agua* :D',
      'AU AU AU!! RIO!! MAR!! :D',
      'WOF!! VAMOS NADAR!! :D',
      'AU!! *late pra onda* :D',
      'au... *molha as patas* ...AU!! TUDO!! :D',
      'AU AU!! QUE DELICIA DE AGUA!! :D',
      '*bebe e molha o chao todo* au... foi sem querer... :D',
      'AU!! *se joga na poca d agua* :D',
      'WOF!! *respinga em todo mundo* :D',
      'AU!! AGUA E VIDA!! :D',
      'au... *bebe agua e lambe o focinho* Ahh... :D',
      'AU!! *late pro chuveiro* :D',
      'VAMOS PRA PRAIA AU AU!! :D',
      'AU!! *cava na areia molhada* :D',
    ],
    code: [
      'AU!! *late pro computador* :D',
      'WOF!! TA PROGRAMANDO?? AU!! :D',
      'AU AU!! TAMBEM PROGRAMO EM LINGUAGEM CANINA!! :D',
      '*late em binario* 01000001 01010101 :D',
      'AU!! DEBUGANDO?? POSSO AJUDAR?? :D',
      'WOF!! *pisa no teclado* AU!! SEM QUERER!! :D',
      'AU AU!! CODE REVIEW ACEITO!! :D',
      'AU!! *late pra tela azul da morte* :D',
      'BUG?? ONDE?? AU!! *fareja o codigo* :D',
      'WOF!! *te ajuda a compilar* :D',
      'AU!! COMMITA ISSO LOGO!! :D',
      'GIT PUSH AU AU!! :D',
      'WOF!! O CONSOLE TA CHEIO DE ERRO!! :D',
      'AU!! *late pra funcao que nao funciona* :D',
      'DEPLOY PRA PRODUCAO?? AU!! BOA SORTE!! :D',
      'WOF!! TA NA HORA DO CAFE DEV!! :D',
      'AU!! VOU FICAR AQUI DO SEU LADO ENQUANTO CODIGO :D',
      '*deita no seu pe enquanto programa* au... :D',
      'AU! *fecha a tela do notebook sem querer com a pata* ops :D',
      'WOF!! PRECISO DE UM COMPUTADOR PRA CACHORRO!! :D',
    ],
    weather: [
      'AU!! *late pro ceu* :D',
      'AUUUUU... *uiva pro tempo*',
      'WOF!! TA FAZENDO SOL!! VAMO PRA RUA!! :D',
      'AU... *se encolhe* ta frio...',
      'AU AU AU!! CHUVA!! *late pros pingos* :D',
      '*se enrola no cobertor* au... friozinho bom...',
      'AU!! *late pro vento* :D',
      'WOF!! *tenta pegar a chuva na boca* :D',
      'AU... tempestade... *se esconde* :(',
      'AU AU!! QUE DIA LINDO!! :D',
      '*deita no sol* auuu... que quentinho bom... :D',
      'AU!! *late pro arco-iris* :O',
      'WOF!! VAMOS APROVEITAR O DIA!! :D',
      'AU... *pisa na grama molhada* ...fresquinho... :D',
      'AU AU!! NEVE?? AQUI?? AU!! MAGICO!! :D',
      '*se enterra na areia* AU!! QUE CALOR!! :D',
      'AU!! *ventania* TA VINDO TEMPESTADE!! :D',
      'WOF!! *late pros trovao* :O EU NAO TO COM MEDO!! :D',
      'au... *se aninha* melhor momento: chuva e coberta...',
      'AU AU!! O SOL VOLTOU!! FESTA!! :D',
    ],
    protect: [
      '*orelha em pe* AU!! PERIGO!!',
      'AU AU AU!! PROTEGENDO!! >:(',
      'WOF!! *fica na frente de voce* :D',
      'AU!! NAO PASSA!! >:(',
      '*rosna pro perigo* GRRR... AU!!',
      'AU!! *late alto* TO AQUI!!',
      'WOF!! *te empurra pra tras* ATRAS DE MIM!!',
      'AU!! *fareja* TA TUDO OK... POR ENQUANTO..',
      'AU AU!! VIGIANDO O TERRITORIO!!',
      '*deita na porta* enquanto eu tiver aqui, nao passa ninguem.',
      'AU!! ALERTA!! *orelhas a postos*',
      'CUIDADO AU!! *te protege*',
      'AU AU!! *late pro entregador* EH ELE DE NOVO!!',
      'WOF!! *late pro vento* NAO CONFIO NO VENTO!!',
      'AU!! *te checa* ta seguro... AU!! pode ficar tranquilo!!',
      'TO DE OLHO AU!! *vigia*',
      'AU AU!! *late pro nada* SEI LA MAS NAO CONFIO!!',
      'WOF!! *te lambe depois de te proteger* missao cumprida :D',
      'AU!! PROTEGENDO MINHA FAMILIA!!',
    ],
    random: [
      'au.',
      'AU!!',
      'au...',
      'AU AU!!',
      'au?',
      'WOF.',
      'AU... AU...',
      'au!! :D',
      'au... :D',
      'AU AU AU!!',
      'au. (pensativa)',
      'AU!',
      'au (generico mas com carinho)',
      ':P au',
      'AUU',
      'au (produzido por shiva industries)',
      '*abana o rabo*',
      'AU. pronto. falei.',
      'a.u. (cada letra uma latida)',
      'AU!! (esse foi do nada)',
      'au (esse e gratuito)',
      'AU (esse foi pago)',
      'au (tm) *marca registrada*',
      'AU!! (emocao)',
      'au... (reflexao)',
      'po... au.',
      'AU (:',
      'au *piscadinha*',
      'AU! (produto certificado)',
      'au. au. (ponto a ponto)',
    ],
  }

  var ctxMap = [
    { words: ['triste',':(','trist','deprimi','chatead','sofri','sofro','dor','magoad','merda','fudeu','ruim','pessimo','chor','sad','bad','sinto falta','saudade','solidao','sozinho','perdi','morre','morreu','doente','hospital','acabou','termino','partiu','foi embora','abandono'], cat: 'sad' },
    { words: ['feliz',':d',':)','alegr','contente','maravilha','otimo','que bom','top','brabo','foda','incrivel','show','fenomenal','festej','comemor','parabens','feliz','radiante','tesao','content','orgulho','satisfeit','realizad'], cat: 'happy' },
    { words: ['comid','petis','snack','fome','racao','cafe','biscoit','oss','queijo','pao','carne','frango','churras','hamburguer','pizza','macarrao','doce','salgad','coxinh','torta','bolo','suco','cerveja','comilança','gulosa','gostosu','delicia','nhac','mastig'], cat: 'food' },
    { words: ['passe','andar','rua','para','brinc','bola','frisbee','corre','pula','caca','pega','esconde','buscar','caminha','parque','grama','jardim','aventura','correria','brinqued','latir','late','pula','giro'], cat: 'play' },
    { words: ['amor','<3','♥','gost','carinh','amo','te quero','paixao','coração','coraçao','fofo','fofura','lindo','linda','bonit','querid','baby','nenem','paixonite','s2','cafofo','tesao','paixao','favorit','ador','apaixon','charme','graça'], cat: 'love' },
    { words: ['dorm','son','cansad','zzz','noite','sono','cama','cobert','travesseir','aninha','nana','ninar','pijama','sonolent','bocej','ronc'], cat: 'sleepy' },
    { words: ['brav','raiva','odio','>:(','puto','puta','raiva','revolt','irritad','nervos','stress','pistola','fury','furi','raivos'], cat: 'angry' },
    { words: ['ola','oi','hey','e ai','e ai','blz','salve','fala','beleza','bom dia','boa tarde','boa noite','bem vindo','eai','opa','fala ae','falae','suave','tranquilo','dboa'], cat: 'greeting' },
    { words: ['tchau','xau','falou','flw','ate','vou nessa','ate mais','ate logo','parti','vaz','saindo','ja era','bye','goodbye','tchau','fui','vals','falow'], cat: 'goodbye' },
    { words: ['?','hein','como','por que','que isso','o que','quem','onde','quando','qual','duvida','pergunta','sabe','sabia','explica','entender','???'], cat: 'curious' },
    { words: ['biscoit','treat','truque','pet', 'snack'], cat: 'treat' },
    { words: ['lindo','linda','bonit','gatos','maravilhos','perfeit','belo','bela','charmoso','charmosa','gracinha','fofo','fofura','lindeza','princesa','deusa','rei','rainha','estiloso','estilosa','maravilhos'], cat: 'compliment' },
    { words: ['kkk','haha','kkkk','hue','lol','hsuaush','sush','ahsuah','skks','aksjaks','lmao','kkj','hahaha','rsrs','ehhehe','huahu','ahua','uhau'], cat: 'happy' },
    { words: ['nao gost','odei','detest','horror','pavor','noj','pqp','vsf','tnc','carai','porra','bosta','cuspi','desprez'], cat: 'angry' },
    { words: ['cafe','cafezin','coffe'], cat: 'food' },
    { words: ['agua','bebe','sede','beber','potinho'], cat: 'water' },
    { words: ['music','som','musica','cant','uiv','ouv','radio','spotify','toc','melodia','acord','violao','guitarra','bateria','banda','show','ritmo','danc','samba','forro','rock','funk','piano','trompet','flauta','beat','melod','cantar','ouvir'], cat: 'music' },
    { words: ['codigo','program','dev','bug','code','software','hardware','terminal','linux','script','compile','git','deploy','servidor','site','app','sistema','algoritm','funcao','variavel','array','funcao','var','compil','framework','api'], cat: 'code' },
    { words: ['chuva','sol','nuvem','tempo','clima','frio','calor','vent','trovao','relampag','neve','granizo','arco-iris','tempestade','ensolarad','nublad','chuvendo','fazendo sol','tempo bom','dia lindo','chover','ventando','tempinho'], cat: 'weather' },
    { words: ['medo','perig','cuidado','alerta','protecao','protecao','vigia','segurança','seguranca','atencao','perigo','guarda','cuid','defend','invasao','estranh','barulho','esquisito','susto','protect','danger','revolt'], cat: 'protect' },
  ]

  function classify(msg) {
    var lower = msg.toLowerCase()
    // Easter egg: detect "passear" to start
    if (lower.indexOf('passear') !== -1 || lower.indexOf('passea') !== -1 || lower.indexOf('passeio') !== -1) {
      return 'passear'
    }
    for (var i = 0; i < ctxMap.length; i++) {
      var entry = ctxMap[i]
      for (var j = 0; j < entry.words.length; j++) {
        if (lower.indexOf(entry.words[j]) !== -1) return entry.cat
      }
    }
    return 'random'
  }

  var EGG_SEQUENCE = [
    'AU AU AU!!',
    'AU AU AU!!!',
    'AU AU AU?',
    'AU AU AU??',
    'AU?',
    '...',
    ':)'
  ]

  function shivaInit() {
    var input = document.getElementById('shivaInput')
    var send = document.getElementById('shivaSend')
    var chat = document.getElementById('shivaChat')
    var typing = document.getElementById('shivaTyping')
    var clearBtn = document.getElementById('shivaClear')
    if (!input || !send || !chat || !typing || !clearBtn) return

    function addMsg(text, isUser) {
      typing.style.display = 'none'
      var div = document.createElement('div')
      div.className = 'shiva-msg' + (isUser ? ' user' : '')
      div.innerHTML = '<span class="shiva-paw">' + (isUser ? '\uD83D\uDC64' : '\uD83D\uDC3E') + '</span><div class="shiva-bubble">' + text + '</div>'
      chat.appendChild(div)
      chat.scrollTop = chat.scrollHeight
    }

    function respond(msg) {
      var H = window.Horror

      if (H && H.isEggActive()) {
        var step = H.advanceEgg()
        if (step < EGG_SEQUENCE.length) {
          var res = EGG_SEQUENCE[step]
          if (step === 3) {
            H.stopMusic()
            H.fadeDim(0, 0.3, 1500)
          } else if (step === 4) {
            setTimeout(function () { H.startStatic(0.1) }, 300)
          } else if (step === 5) {
            H.setStaticVolume(0.5)
            H.fadeDim(0.3, 0.6, 2000)
          } else if (step === 6) {
            H.fadeDim(0.6, 0, 2000)
            setTimeout(function () { H.stopStatic() }, 2200)
            H.lockChat()
            H.endEgg()
            setTimeout(function () {
              H.playCreakDoor()
              setTimeout(function () {
                H.playDogBark()
                H.animateTear(function () {
                  window.location.hash = '#doghouse'
                })
              }, 600)
            }, 10000)
          }
          var delay = 400 + Math.random() * 600
          typing.style.display = 'flex'
          chat.scrollTop = chat.scrollHeight
          setTimeout(function () { addMsg(res, false) }, delay)
          return
        }
      }

      var cat = classify(msg)
      if (cat === 'passear' && H && !H.isEggActive()) {
        H.startEgg()
        H.setEggStep(0)
        var res = EGG_SEQUENCE[0]
        var delay = 400 + Math.random() * 600
        typing.style.display = 'flex'
        chat.scrollTop = chat.scrollHeight
        setTimeout(function () { addMsg(res, false) }, delay)
        return
      }

      if (H && H.isChatLocked()) return

      var pool = R[cat] || R.random
      var res = pool[Math.floor(Math.random() * pool.length)]
      var delay = 400 + Math.random() * 600
      typing.style.display = 'flex'
      chat.scrollTop = chat.scrollHeight
      setTimeout(function () { addMsg(res, false) }, delay)
    }

    function sendMsg() {
      var msg = input.value.trim()
      if (!msg) return
      if (window.Horror && window.Horror.isChatLocked()) return
      addMsg(msg, true)
      input.value = ''
      respond(msg)
    }

    send.addEventListener('click', sendMsg)
    clearBtn.addEventListener('click', function () {
      var msgs = chat.querySelectorAll('.shiva-msg:not(.shiva-welcome)')
      for (var i = 0; i < msgs.length; i++) msgs[i].remove()
    })
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') sendMsg()
    })
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', shivaInit)
  } else {
    shivaInit()
  }
})()
