name: Sort Rankings
on: workflow_dispatch
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sort JSONs
        run: python3 data/rankings/sort-rankings.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Ordena rankings automaticamente"
